# Plot Summary

Create publication-ready visualizations of PyPSA optimization results including energy balances, installed capacities, and system costs.

**How to use:**
1. Run `make_stats_dict.py` to extract statistics from network files
2. Update `plot_summary.yaml` with your experiment configuration (countries, years, scenarios)
3. Execute cells below to generate all plots automatically

**Configuration:** Edit `plot_summary.yaml` to switch between experiments, filter scenarios, or adjust plot styling without changing code.

**Environment:** Install `envs/pypsa-earth-vis.yaml`

In [105]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=DeprecationWarning)
import plotly.express as px

from plot_helpers import (
    chdir_to_root_dir,
    read_stats_dict,
    read_csv_nafix,
    prepare_dataframe,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_co2_stored,
    rename_costs,
    rename_stores,
    rename_h2o,
    colors,
    save_plotly_fig,
    export_plotly_figure,
    get_scen_col_function,
    apply_standard_styling,
    update_layout,
    plot_energy_balance,
    plot_capacity,
    plot_gwkm,
    h2o_cost_bar_fig,
    load_plot_config,
    register_template,
    build_ptx_exports_df,
    build_ptx_exports_h2_equiv_df,
    build_maritime_df,
    build_aviation_df,
    INDEX_COLS
)

chdir_to_root_dir()
register_template()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [106]:
# Load configuration from YAML file
yaml_config = load_plot_config()

# Extract configuration
RUN_NAME_PREFIX = yaml_config['run']['name_prefix']
SUMMARY_VERSION = yaml_config['run']['summary_version']
SDIR = Path.cwd() / "results" / f"{RUN_NAME_PREFIX}_summary_{SUMMARY_VERSION}"
SDIR.mkdir(exist_ok=True, parents=True)

COUNTRIES = yaml_config['data']['countries']
YEARS = yaml_config['data']['years']
INDEX_LEVELS_TO_DROP = yaml_config['data']['index_levels_to_drop']

# Build index group
IDX_GROUP = idx_slice[[RUN_NAME_PREFIX], :, COUNTRIES, YEARS]
IDX_GROUP_NAME = "".join(COUNTRIES) + "_MAIN"

print(f"Index Group Name: {IDX_GROUP_NAME}")
print(f"Index Group: {IDX_GROUP}")

# Scenario filtering
SCEN_FILTER = yaml_config['data']['scen_filter']
scen_order = yaml_config['data']['scen_order']

# Get scenario column function
scen_col_func_name = yaml_config['data']['scen_col_function']
set_scen_col = get_scen_col_function(scen_col_func_name)
print(f"Using scenario column function: {scen_col_func_name}")

# Plot dimensions
width = yaml_config['plot']['width']
heights = yaml_config['plot']['heights']

# Default figure kwargs
fig_kwargs = yaml_config['plot']['default_kwargs'].copy()
fig_kwargs['width'] = width
fig_kwargs['height'] = heights['medium']

print(f"\nConfiguration loaded successfully!")
print(f"Countries: {COUNTRIES}")
print(f"Years: {YEARS}")
print(f"Scenario filter: {SCEN_FILTER if SCEN_FILTER else 'None (show all)'}")

Index Group Name: MA_MAIN
Index Group: (['WSA'], slice(None, None, None), ['MA'], [2050])
Using scenario column function: WSA

Configuration loaded successfully!
Countries: ['MA']
Years: [2050]
Scenario filter: None (show all)

In [107]:
# Load data dictionaries using configuration
balance_keys = yaml_config['carriers']['balance']
capacity_keys = yaml_config['carriers']['capacity']
cost_keys = yaml_config['carriers']['costs']

balance_dict = read_stats_dict("balance_dict", SDIR, keys=balance_keys)
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", SDIR, keys=capacity_keys)
costs_dict = read_stats_dict("costs_dict", SDIR, keys=cost_keys)

# Load stores data (storage volume capacities)
try:
    stores = read_csv_nafix(SDIR / "stores.csv")
    print(f"Loaded stores data: {stores.shape}")
except FileNotFoundError:
    stores = None
    print("⚠️  stores.csv not found — stores_capacity chart will be skipped")

print(f"Loaded balance data for: {balance_keys}")
print(f"Loaded capacity data for: {capacity_keys}")
print(f"Loaded cost data for: {cost_keys}")

Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_H2.csv
Imported oil from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_oil.csv
Imported gas from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_gas.csv
Imported co2 stored from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_co2 stored.csv
Imported co2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_co2.csv

Imported NH3 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_NH3.csv
Imported methanol from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_methanol.csv
Imported HBI from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_HBI.csv
⚠️  Empty data in /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_H2O.csv — skipping 'H2O'
Imported purewater from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_purewater.csv
Imported seawater from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/balance_dict_seawater.csv
Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/optimal_capacity_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/optimal_capacity_dict_H2.csv
Imported HBI from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/optimal_capacity_dict_HBI.csv
Imported capex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/costs_dict_capex.csv
Imported opex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/costs_dict_opex.csv
Loaded stores data: (2, 16)
Loaded balance data for: ['AC', 'H2', 'oil', 'gas', 'co2 stored', 'co2', 'NH3', 'methanol', 'HBI', 'H2O', 'purewater', 'seawater']
Loaded capacity data for: ['AC', 'H2', 'HBI']
Loaded cost data for: ['capex', 'opex']

In [108]:
# Load grid km data (requires index_col so plot_gwkm can slice by idx_group)
try:
    gwkm_ac = read_csv_nafix(SDIR / "gwkm_dict_AC.csv", index_col=INDEX_COLS)
    print(f"Loaded Grid km (AC): {gwkm_ac.shape}")
except FileNotFoundError:
    gwkm_ac = None
    print("⚠️  gwkm_dict_AC.csv not found — Grid km (AC) chart will be skipped")

try:
    gwkm_h2 = read_csv_nafix(SDIR / "gwkm_dict_H2 pipeline.csv", index_col=INDEX_COLS)
    print(f"Loaded Grid km (H2 pipeline): {gwkm_h2.shape}")
except FileNotFoundError:
    gwkm_h2 = None
    print("⚠️  gwkm_dict_H2 pipeline.csv not found — Grid km (H2 pipeline) chart will be skipped")

Loaded Grid km (AC): (2, 4)
Loaded Grid km (H2 pipeline): (2, 4)

## Plots

In [109]:
plot_config = {
    'idx_group': IDX_GROUP,
    'idx_group_name': IDX_GROUP_NAME,
    'index_levels_to_drop': INDEX_LEVELS_TO_DROP,
    'set_scen_col_func': set_scen_col,
    'scen_filter': SCEN_FILTER,
    'scen_order': scen_order,
    'fig_kwargs': fig_kwargs,
    'heights': heights,
    'flip_axes': False,
    'show_totals': True,
}

### Electricity Supply

In [110]:
balance_dict["AC"]

                                                                                                                  AC  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -62.7
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -62.7

                                                                                                                BEV charger  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5        -47.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5        -47.0

                                                                                                                CCGT  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0

                                                                                                                DAC  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -4.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -4.0

                                                                                                                DRI  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -5.6
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -5.6

                                                                                                                EAF  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -3.5
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5 -3.5

                                                                                                                Fischer-Tropsch  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5             -0.3
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5             -0.3

                                                                                                                H2 Electrolysis  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           -219.6
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           -219.7

                                                                                                                H2 Fuel Cell  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           0.0

                                                                                                                H2 turbine  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0

                                                                                                                ...  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts   ...
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  ...
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  ...

                                                                                                                services rural resistive heater  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                             -0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                             -0.0

                                                                                                                services urban decentral air heat pump  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                    -0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                    -0.0

                                                                                                                services urban decentral resistive heater  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                       -0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                       -0.0

                                                                                                                solar  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  537.8
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  651.3

                                                                                                                urban central air heat pump  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                         -2.7
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                         -2.9

                                                                                                                urban central gas CHP  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                    0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                    0.0

                                                                                                                urban central gas CHP CC  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                       0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                       0.0

                                                                                                                urban central resistive heater  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                            -0.6
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                            -0.3

                                                                                                                urban central solid biomass CHP  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                              0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                              0.0

                                                                                                                urban central solid biomass CHP CC
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                 0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                 0.0

[2 rows x 46 columns]

In [111]:
plot_config['chart_config'] = yaml_config['charts']['electricity_supply']

fig, df = plot_energy_balance(
    carrier="AC",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_electricity,
    show_supply=True,
    save_dir=SDIR
)

fig.show()

### Electricity Demand

In [112]:
plot_config['chart_config'] = yaml_config['charts']['electricity_demand']

fig, df = plot_energy_balance(
    carrier="AC",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_electricity,
    show_supply=False,
    save_dir=SDIR
)

fig.show()

### Electricity Installed Capacity

In [113]:
optimal_capacity_dict["AC"]

                                                                                                                CCGT  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0

                                                                                                                H2 Fuel Cell  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           0.0

                                                                                                                H2 turbine  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0

                                                                                                                OCGT  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5   0.0

                                                                                                                PHS  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.8
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.8

                                                                                                                battery discharger  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                78.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                84.9

                                                                                                                biomass EOP  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5          0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5          0.0

                                                                                                                hydro  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5    1.2
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5    1.2

                                                                                                                load shedding  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           13.8
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5           13.8

                                                                                                                offwind-dc  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5         0.0

                                                                                                                oil  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.8
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.8

                                                                                                                onwind  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5    43.3
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5    14.1

                                                                                                                ror  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.5
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  0.5

                                                                                                                solar  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  337.7
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5  413.6

                                                                                                                urban central gas CHP  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                    0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                    0.0

                                                                                                                urban central gas CHP CC  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                       0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                       0.0

                                                                                                                urban central solid biomass CHP  \
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                              0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                              0.0

                                                                                                                urban central solid biomass CHP CC
run_name_prefix run_name            country year simpl clusters ll   opts     sopts discountrate demand eopts
WSA             WSA_MA_2050_low50   MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                 0.0
                WSA_MA_2050_vestas3 MA      2050 NaN   10       v1.2 Co2L0.17 1H    0.084        RF     H2v0.5                                 0.0

In [114]:
plot_config['chart_config'] = yaml_config['charts']['electricity_capacity']

fig, df = plot_capacity(
    carrier="AC",
    capacity_dict=optimal_capacity_dict,
    config=plot_config,
    rename_function=rename_electricity,
    save_dir=SDIR
)

fig.show()

### Hydrogen Balance

In [115]:
plot_config['chart_config'] = yaml_config['charts']['hydrogen_balance']

fig, df = plot_energy_balance(
    carrier="H2",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_h2,
    save_dir=SDIR
)

fig.show()

### Hydrogen Installed Capacity

In [116]:
plot_config['chart_config'] = yaml_config['charts']['hydrogen_capacity']

fig, df = plot_capacity(
    carrier="H2",
    capacity_dict=optimal_capacity_dict,
    config=plot_config,
    rename_function=rename_h2,
    save_dir=SDIR
)

fig.show()

### Liquid Fuel Balance

In [117]:
plot_config['chart_config'] = yaml_config['charts']['liquid_fuel_balance']

fig, df = plot_energy_balance(
    carrier="oil",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_oil,
    save_dir=SDIR
)

fig.show()

### CH4 Balance

In [118]:
plot_config['chart_config'] = yaml_config['charts']['ch4_balance']

fig, df = plot_energy_balance(
    carrier="gas",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_gas,
    save_dir=SDIR
)

fig.show()

### CO2 Capture and Usage

In [119]:
plot_config['chart_config'] = yaml_config['charts']['co2_stored_balance']

fig, df = plot_energy_balance(
    carrier="co2 stored",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_co2_stored,
    save_dir=SDIR
)

fig.show()

### CO2 Emissions

In [120]:
plot_config['chart_config'] = yaml_config['charts']['co2_emissions']

fig, df = plot_energy_balance(
    carrier="co2",
    balance_dict=balance_dict,
    config=plot_config,
    rename_function=rename_co2,
    save_dir=SDIR
)

fig.show()

### Water Balance (Purewater & Seawater)

In [121]:
# Both h2g-vis ("H2O") and DKS ("purewater"/"seawater") carriers are listed;
# missing ones are silently skipped.
for water_carrier, chart_key in [
    ("H2O",       "water_balance"),       # h2g-vis naming
    ("purewater",  "purewater_balance"),   # DKS naming
    ("seawater",   "seawater_balance"),    # DKS naming
]:
    if water_carrier in balance_dict:
        plot_config['chart_config'] = yaml_config['charts'][chart_key]
        fig, df = plot_energy_balance(
            carrier=water_carrier,
            balance_dict=balance_dict,
            config=plot_config,
            rename_function=rename_h2o,
            save_dir=SDIR
        )
        fig.show()
    else:
        print(f"⚠️  '{water_carrier}' not in balance_dict — skipping")

⚠️  'H2O' not in balance_dict — skipping

### Storage Volume Capacity

In [122]:
if stores is not None:
    plot_config['chart_config'] = yaml_config['charts']['stores_capacity']

    # Use plot_capacity the same way app.py does
    stores_indexed = stores.set_index(INDEX_COLS) if not isinstance(stores.index, pd.MultiIndex) else stores

    fig, stores_df = plot_capacity(
        carrier="stores",
        capacity_dict={"stores": stores_indexed},
        config=plot_config,
        rename_function=rename_stores,
        save_dir=SDIR
    )
    fig.show()
else:
    print("⚠️  stores data not loaded — skipping stores_capacity chart")

### System Costs

In [123]:
plot_config['chart_config'] = yaml_config['charts'].get('system_costs', {
    'title': 'System Costs',
    'save_name': 'system_costs_billion_eur',
    'chart_type': 'bar_with_negatives'
})
stats_df = pd.concat([costs_dict["capex"], costs_dict["opex"]], axis=0)
df = prepare_dataframe(
    stats_df, IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
    rename_function=rename_costs,
)
df = df[df["value"] != 0]
df = df.query("scen in @SCEN_FILTER") if SCEN_FILTER else df

fig_kwargs_costs = plot_config['fig_kwargs'].copy()
fig_kwargs_costs['height'] = plot_config['heights']['large']

fig = px.bar(
    df,
    **fig_kwargs_costs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable": list(colors["costs"].keys()),
        "scen": scen_order
    },
    labels={
        "value": "System costs (billion EUR/year)",
        "year": "",
        "scen": ""
    }
)

chart_type = plot_config['chart_config'].get('chart_type', 'bar')
fig = apply_standard_styling(fig, chart_type, plot_config['chart_config'])
update_layout(fig, flip_axes=plot_config.get('flip_axes', False))

save_name = plot_config['chart_config'].get('save_name', 'system_costs')
save_plotly_fig(df, fig, SDIR, f"{IDX_GROUP_NAME}_{save_name}")

fig.show()

### PtX Export Volumes

In [124]:
# ── PtX Export Volumes (TWh) ──────────────────────────────────────────────
df_exports = build_ptx_exports_df(
    balance_dict,
    COUNTRIES, YEARS,
    set_scen_col,
    INDEX_LEVELS_TO_DROP,
    scen_filter=SCEN_FILTER,
    sdir=SDIR,
)

_fk = fig_kwargs.copy()
_fk["height"] = heights["medium"]

fig_exp = px.bar(
    df_exports,
    **_fk,
    color_discrete_map=colors["export_ptx"],
    category_orders={
        "variable": list(colors["export_ptx"].keys()),
        "scen": scen_order if scen_order else None,
    },
    labels={
        "value": "PtX export volume (TWh)",
        "year": "",
        "scen": "",
        "variable": "",
    },
)
fig_exp = apply_standard_styling(fig_exp, "bar", {"chart_type": "bar"})
update_layout(fig_exp, flip_axes=plot_config.get("flip_axes", False))
save_plotly_fig(df_exports, fig_exp, SDIR, f"{IDX_GROUP_NAME}_ptx_export_TWh")
fig_exp.show()

### PtX Export Volumes (H₂ equivalent)

In [125]:
# ── PtX Export Volumes in H₂ equivalent (TWh_H2) ─────────────────────────
df_exports_h2eq = build_ptx_exports_h2_equiv_df(
    balance_dict,
    COUNTRIES, YEARS,
    set_scen_col,
    INDEX_LEVELS_TO_DROP,
    scen_filter=SCEN_FILTER,
    sdir=SDIR,
)

_fk = fig_kwargs.copy()
_fk["height"] = heights["medium"]

fig_exp_h2eq = px.bar(
    df_exports_h2eq,
    **_fk,
    color_discrete_map=colors["export_ptx_h2eq"],
    category_orders={
        "variable": list(colors["export_ptx_h2eq"].keys()),
        "scen": scen_order if scen_order else None,
    },
    labels={
        "value": "PtX export H₂ equivalent (TWh)",
        "year": "",
        "scen": "",
        "variable": "",
    },
)
fig_exp_h2eq = apply_standard_styling(fig_exp_h2eq, "bar", {"chart_type": "bar"})
update_layout(fig_exp_h2eq, flip_axes=plot_config.get("flip_axes", False))
save_plotly_fig(df_exports_h2eq, fig_exp_h2eq, SDIR, f"{IDX_GROUP_NAME}_ptx_export_H2eq_TWh")
fig_exp_h2eq.show()

### Maritime Fuel Demand

In [126]:
# ── Maritime Fuel Demand (TWh) ────────────────────────────────────────────
df_maritime = build_maritime_df(
    balance_dict,
    COUNTRIES, YEARS,
    set_scen_col,
    INDEX_LEVELS_TO_DROP,
    scen_filter=SCEN_FILTER,
)

_fk_m = fig_kwargs.copy()
_fk_m["height"] = heights["medium"]

fig_maritime = px.bar(
    df_maritime,
    **_fk_m,
    color_discrete_map=colors["maritime"],
    category_orders={
        "variable": list(colors["maritime"].keys()),
        "scen": scen_order if scen_order else None,
    },
    labels={
        "value": "Maritime fuel demand (TWh)",
        "year": "", "scen": "", "variable": "",
    },
)
fig_maritime = apply_standard_styling(fig_maritime, "bar", {"chart_type": "bar"})
update_layout(fig_maritime, flip_axes=plot_config.get("flip_axes", False))
save_plotly_fig(df_maritime, fig_maritime, SDIR, f"{IDX_GROUP_NAME}_maritime_demand_TWh")
fig_maritime.show()

### Aviation Fuel Demand

In [127]:
# ── Aviation Fuel Demand (TWh) ────────────────────────────────────────────
df_aviation = build_aviation_df(
    balance_dict,
    COUNTRIES, YEARS,
    set_scen_col,
    INDEX_LEVELS_TO_DROP,
    scen_filter=SCEN_FILTER,
)

_fk_a = fig_kwargs.copy()
_fk_a["height"] = heights["medium"]

fig_aviation = px.bar(
    df_aviation,
    **_fk_a,
    color_discrete_map=colors["aviation"],
    category_orders={
        "variable": list(colors["aviation"].keys()),
        "scen": scen_order if scen_order else None,
    },
    labels={
        "value": "Aviation fuel demand (TWh)",
        "year": "", "scen": "", "variable": "",
    },
)
fig_aviation = apply_standard_styling(fig_aviation, "bar", {"chart_type": "bar"})
update_layout(fig_aviation, flip_axes=plot_config.get("flip_axes", False))
save_plotly_fig(df_aviation, fig_aviation, SDIR, f"{IDX_GROUP_NAME}_aviation_demand_TWh")
fig_aviation.show()

In [128]:
if gwkm_ac is not None:
    plot_config['chart_config'] = yaml_config['charts'].get('grid_km_ac', {
        'title': 'Grid km (AC)',
        'save_name': 'grid_km_AC',
        'chart_type': 'bar',
    })
    fig, gwkm_ac_df = plot_gwkm(gwkm_ac, config=plot_config)
    save_plotly_fig(gwkm_ac_df, fig, SDIR, f"{IDX_GROUP_NAME}_grid_km_AC")
    fig.show()
else:
    print("⚠️  gwkm_dict_AC.csv not loaded — skipping")

### Grid km (H2 Pipeline)

In [129]:
if gwkm_h2 is not None:
    plot_config['chart_config'] = yaml_config['charts'].get('grid_km_h2_pipeline', {
        'title': 'Grid km (H2 Pipeline)',
        'save_name': 'grid_km_H2_pipeline',
        'chart_type': 'bar',
    })
    fig, gwkm_h2_df = plot_gwkm(gwkm_h2, config=plot_config)
    save_plotly_fig(gwkm_h2_df, fig, SDIR, f"{IDX_GROUP_NAME}_grid_km_H2_pipeline")
    fig.show()
else:
    print("⚠️  gwkm_dict_H2 pipeline.csv not loaded — skipping")

### Water Cost Breakdown

In [130]:
# H2O cost components (union of DKS and h2g-vis naming)
_H2O_COMPONENTS = [
    "desalination", "seawater", "H2O pipeline",
    "H2O store", "H2O store charger", "H2O store discharger",
    "H2O generator",
]

try:
    _capex = read_csv_nafix(SDIR / "costs_dict_capex.csv")
    _opex  = read_csv_nafix(SDIR / "costs_dict_opex.csv")
    _h2    = read_csv_nafix(SDIR / "balance_dict_H2.csv")

    def _filt(df):
        return df[df["country"].isin(COUNTRIES) & df["year"].isin(YEARS)].copy()

    capex_f, opex_f, h2_f = _filt(_capex), _filt(_opex), _filt(_h2)

    present_comps = [c for c in _H2O_COMPONENTS if c in capex_f.columns or c in opex_f.columns]
    if not present_comps:
        raise ValueError("No H2O cost components found in capex/opex CSVs")

    _IDX = list(INDEX_COLS)
    cap_sub = capex_f[_IDX + [c for c in present_comps if c in capex_f.columns]].rename(
        columns={c: f"{c}__cap" for c in present_comps if c in capex_f.columns}
    )
    opx_sub = opex_f[_IDX + [c for c in present_comps if c in opex_f.columns]].rename(
        columns={c: f"{c}__opx" for c in present_comps if c in opex_f.columns}
    )
    combined = cap_sub.merge(opx_sub, on=_IDX, how="inner")

    h2o_costs = combined[_IDX].copy()
    for comp in present_comps:
        cap_v = combined[f"{comp}__cap"].fillna(0) if f"{comp}__cap" in combined.columns else 0.0
        opx_v = combined[f"{comp}__opx"].fillna(0) if f"{comp}__opx" in combined.columns else 0.0
        h2o_costs[comp] = cap_v + opx_v

    h2_elec = h2_f[_IDX + ["H2 Electrolysis"]].copy()
    h2_elec["H2 Electrolysis"] = h2_elec["H2 Electrolysis"].abs()

    df_h2o = h2o_costs.merge(h2_elec, on=_IDX, how="inner")
    for comp in present_comps:
        df_h2o[comp] = df_h2o[comp] / df_h2o["H2 Electrolysis"] * 1000  # bn€/TWh → €/MWh_H2

    df_h2o = set_scen_col(df_h2o, index_levels_to_drop=INDEX_LEVELS_TO_DROP)
    df_scen = df_h2o[["country", "year", "scen"] + present_comps].copy()
    df_scen = df_scen.query("scen in @SCEN_FILTER") if SCEN_FILTER else df_scen
    df_scen["total"] = df_scen[present_comps].sum(axis=1)

    nonzero_comps = [c for c in present_comps if df_scen[c].abs().max() > 0.01]
    comp_colors = yaml_config['charts']['h2o_cost_breakdown']['color_discrete_map']

    for year_val in YEARS:
        fig = h2o_cost_bar_fig(
            df_scen,
            year=year_val,
            components=nonzero_comps,
            scen_order_list=scen_order,
            component_colors=comp_colors,
            show_totals=plot_config.get('show_totals', True),
            flip_axes=plot_config.get('flip_axes', False),
        )
        fig.show()

except FileNotFoundError as e:
    print(f"⚠️  H2O cost data not available: {e} — skipping water cost breakdown")
except (ValueError, KeyError) as e:
    print(f"⚠️  H2O cost data processing error: {e} — skipping water cost breakdown")

### Scenario Comparison: Percentage Differences

Collects key result scalars per scenario and shows their relative (%) difference with respect to the **reference scenario** (first in `scen_order`, or the first one found in the data).

| Variable | Unit |
|---|---|
| Solar PV optimal capacity | GW |
| Wind onshore optimal capacity | GW |
| Solar PV electricity supply | TWh |
| Wind onshore electricity supply | TWh |
| H2 Electrolysis optimal capacity | GW |
| H2 Tank storage capacity | TWh |
| Total system costs (capex + opex) | bn €/yr |
| Load-weighted H2 export price | €/MWh_H2 |

In [132]:
# ── Collect key metrics per scenario ─────────────────────────────────────────
_metrics      = {}  # metric_name → pd.Series(scen → value)
_units        = {}  # metric_name → unit string
_display_names = {}  # metric_name → display label override (without unit)

def _scen_agg(df_long, variable_name, agg="sum"):
    """Sum (or mean) a single variable from a prepare_dataframe long-format result."""
    sub = df_long[df_long["variable"] == variable_name]
    if sub.empty:
        return pd.Series(dtype=float, name=variable_name)
    g = sub.groupby("scen")["value"]
    return (g.sum() if agg == "sum" else g.mean()).rename(variable_name)

# --- Solar PV & Wind onshore capacity (GW) ---
if "AC" in optimal_capacity_dict:
    _df_ac = prepare_dataframe(
        optimal_capacity_dict["AC"], IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
        rename_function=rename_electricity
    )
    for _var, _unit in [("Solar PV", "GW"), ("Wind onshore", "GW")]:
        s = _scen_agg(_df_ac, _var)
        if not s.empty:
            _metrics[_var] = s
            _units[_var]   = _unit

# --- Solar PV & Wind onshore electricity supply (TWh) ---
# Keys use " supply" suffix to avoid collision with capacity; display names drop it.
if "AC" in balance_dict:
    _df_ac_bal = prepare_dataframe(
        balance_dict["AC"], IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
        rename_function=rename_electricity
    )
    _df_ac_supply = _df_ac_bal[_df_ac_bal["value"] > 0]
    for _var in ["Solar PV", "Wind onshore"]:
        s = _scen_agg(_df_ac_supply, _var)
        if not s.empty:
            _key = f"{_var} supply"
            _metrics[_key]       = s
            _units[_key]         = "TWh"
            _display_names[_key] = _var  # show as "Solar PV (TWh)", not "Solar PV supply (TWh)"

# --- H2 Electrolysis capacity (GW) ---
if "H2" in optimal_capacity_dict:
    _df_h2cap = prepare_dataframe(
        optimal_capacity_dict["H2"], IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
        rename_function=rename_h2
    )
    s = _scen_agg(_df_h2cap, "H2 Electrolysis")
    if not s.empty:
        _metrics["H2 Electrolysis"] = s
        _units["H2 Electrolysis"]   = "GW"

# --- H2 Tank / H2 Underground storage capacity (TWh) ---
if stores is not None:
    _stores_idx = stores.set_index(INDEX_COLS) if not isinstance(stores.index, pd.MultiIndex) else stores
    _df_st = prepare_dataframe(
        _stores_idx, IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
        rename_function=rename_stores
    )
    for _var in ["H2 Tank", "H2 Underground storage"]:
        s = _scen_agg(_df_st, _var)
        if not s.empty:
            _metrics[_var] = s
            _units[_var]   = "TWh"

# --- Total system costs (bn €/yr) ---
_costs_concat = pd.concat([costs_dict["capex"], costs_dict["opex"]], axis=0)
_df_costs_all = prepare_dataframe(
    _costs_concat, IDX_GROUP, INDEX_LEVELS_TO_DROP, set_scen_col,
    rename_function=rename_costs
)
s_costs = _df_costs_all.groupby("scen")["value"].sum()
if not s_costs.empty:
    _metrics["System costs"] = s_costs
    _units["System costs"]   = "bn €/yr"

# --- Marginal prices: H2 export, HBI ---
# Loaded from marginal_prices_prepared.csv (long format: scen, year, country, variable, value)
try:
    _mpp = read_csv_nafix(SDIR / "marginal_prices_prepared.csv")
    _mpp_f = _mpp[
        _mpp["country"].isin(COUNTRIES) & _mpp["year"].isin(YEARS)
    ].copy()
    if SCEN_FILTER:
        _mpp_f = _mpp_f.query("scen in @SCEN_FILTER")

    _avail_vars = _mpp_f["variable"].dropna().unique()
    print(f"Available price variables: {list(_avail_vars)}")

    _price_specs = [
        ("H2 export price", lambda v: "H2" in str(v) and "export" in str(v).lower(), "EUR/MWh_H2"),
        ("HBI price",        lambda v: "HBI" in str(v),                               "EUR/MWh_HBI"),
    ]
    for _pkey, _matcher, _unit in _price_specs:
        _pvar = next((v for v in _avail_vars if _matcher(v)), None)
        if _pvar:
            s_p = _mpp_f[_mpp_f["variable"] == _pvar].groupby("scen")["value"].mean()
            _metrics[_pkey] = s_p
            _units[_pkey]   = _unit
            print(f"✓  {_pkey}: '{_pvar}'")
        else:
            print(f"⚠️  No variable found for '{_pkey}'")
except FileNotFoundError:
    print("⚠️  marginal_prices_prepared.csv not found — skipping price metrics")

# ── Summary table (absolute values) ─────────────────────────────────────────
summary = pd.DataFrame(_metrics).T.rename_axis("metric").rename_axis("scenario", axis=1)
print("\nKey metrics — absolute values:")
display(summary.round(2))

Available price variables: ['Earth HBI', 'Earth purewater', 'Earth steel', 'FT export', 'H2 export', 'MA.10_1_AC H2', 'MA.10_1_AC NH3', 'MA.10_1_AC industry methanol', 'MA.10_1_AC shipping methanol', 'MA.11_1_AC H2', 'MA.11_1_AC NH3', 'MA.11_1_AC industry methanol', 'MA.11_1_AC shipping methanol', 'MA.12_1_AC H2', 'MA.12_1_AC NH3', 'MA.12_1_AC industry methanol', 'MA.12_1_AC seawater', 'MA.12_1_AC shipping methanol', 'MA.13_1_AC H2', 'MA.13_1_AC NH3', 'MA.13_1_AC industry methanol', 'MA.13_1_AC shipping methanol', 'MA.14_1_AC H2', 'MA.14_1_AC NH3', 'MA.14_1_AC industry methanol', 'MA.14_1_AC seawater', 'MA.14_1_AC shipping methanol', 'MA.15_1_AC H2', 'MA.15_1_AC NH3', 'MA.15_1_AC industry methanol', 'MA.15_1_AC shipping methanol', 'MA.1_1_AC H2', 'MA.1_1_AC NH3', 'MA.1_1_AC industry methanol', 'MA.1_1_AC shipping methanol', 'MA.2_1_AC H2', 'MA.2_1_AC NH3', 'MA.2_1_AC industry methanol', 'MA.2_1_AC seawater', 'MA.2_1_AC shipping methanol', 'MA.3_1_AC H2', 'MA.3_1_AC NH3', 'MA.3_1_AC industry methanol', 'MA.3_1_AC shipping methanol', 'MA.4_1_AC H2', 'MA.4_1_AC NH3', 'MA.4_1_AC industry methanol', 'MA.4_1_AC seawater', 'MA.4_1_AC shipping methanol', 'MA.5_1_AC H2', 'MA.5_1_AC NH3', 'MA.5_1_AC industry methanol', 'MA.5_1_AC seawater', 'MA.5_1_AC shipping methanol', 'MA.6_1_AC H2', 'MA.6_1_AC NH3', 'MA.6_1_AC industry methanol', 'MA.6_1_AC shipping methanol', 'MA.7_1_AC H2', 'MA.7_1_AC NH3', 'MA.7_1_AC industry methanol', 'MA.7_1_AC shipping methanol', 'MA.8_1_AC H2', 'MA.8_1_AC NH3', 'MA.8_1_AC industry methanol', 'MA.8_1_AC shipping methanol', 'MA.9_1_AC H2', 'MA.9_1_AC NH3', 'MA.9_1_AC industry methanol', 'MA.9_1_AC shipping methanol', 'NH3 export']
✓  H2 export price: 'H2 export'
✓  HBI price: 'Earth HBI'

Key metrics — absolute values:

scenario             low50  vestas3
metric
Solar PV             337.7    413.6
Wind onshore          43.3     14.1
Solar PV supply      537.8    651.3
Wind onshore supply  154.7     41.0
H2 Electrolysis       31.7     39.4
H2 Tank               25.1     78.5
System costs          42.9     44.2
H2 export price      166.5    169.6
HBI price            679.0    690.7

In [133]:
# ── % difference plot ────────────────────────────────────────────────────────
_all_scens = summary.columns.tolist()

if len(_all_scens) < 2:
    print("ℹ️  Only one scenario found — no percentage differences to plot.")
else:
    # Use vestas3 as reference if available, otherwise first scenario
    _ref_scen = "vestas3" if "vestas3" in _all_scens else _all_scens[0]
    _other_scens = [s for s in _all_scens if s != _ref_scen]
    print(f"Reference scenario: '{_ref_scen}'")

    pct_diff = (
        summary
        .subtract(summary[_ref_scen], axis=0)
        .div(summary[_ref_scen].abs(), axis=0)
        .mul(100)
        .drop(columns=[_ref_scen], errors="ignore")
    )

    # Label rows with units (use _display_names override when set, e.g. "Solar PV" not "Solar PV supply")
    _metric_labels = [f"{_display_names.get(m, m)} ({_units.get(m, '?')})" for m in summary.index]
    pct_diff.index = _metric_labels
    pct_diff.index.name = "metric"

    df_pct = (
        pct_diff
        .reset_index()
        .melt(id_vars="metric", var_name="scen", value_name="Δ (%)")
        .dropna(subset=["Δ (%)"])
    )

    print("\nPercentage differences:")
    display(pct_diff.round(1))

    _cat_orders = {}
    if scen_order:
        _cat_orders["scen"] = scen_order

    fig_pct = px.bar(
        df_pct,
        x="metric",
        y="Δ (%)",
        color="scen",
        barmode="group",
        width=width,
        height=heights["medium"],
        text_auto=".1f",
        labels={"metric": "", "Δ (%)": f"% difference vs '{_ref_scen}'", "scen": ""},
        title=f"Scenario comparison — % difference vs <b>{_ref_scen}</b>",
        category_orders=_cat_orders,
    )
    fig_pct.add_hline(y=0, line_width=1.5, line_color="black")
    fig_pct.update_yaxes(range=[-100, 100])
    fig_pct.update_xaxes(tickangle=-25)
    update_layout(fig_pct)
    save_plotly_fig(df_pct, fig_pct, SDIR, f"{IDX_GROUP_NAME}_scenario_pct_diff")
    fig_pct.show()

    # ── LaTeX table ───────────────────────────────────────────────────────────
    def _fmt_num(val):
        """Format a numeric value for LaTeX with thousands separator."""
        if pd.isna(val):
            return "---"
        prefix = "$-$" if val < 0 else ""
        v = abs(val)
        if v >= 1000:
            s = f"{v:,.0f}".replace(",", "{,}")
        elif v >= 100:
            s = f"{v:.0f}"
        elif v >= 10:
            s = f"{v:.1f}"
        elif v >= 1:
            s = f"{v:.2f}"
        else:
            s = f"{v:.3f}"
        return prefix + s

    def _fmt_pct(val):
        """Format a percentage change for LaTeX."""
        if pd.isna(val):
            return "---"
        sign = "+" if val >= 0 else ""
        return f"${sign}{val:.0f}\\%$"

    def _tex_escape(s):
        """Escape LaTeX special characters in text."""
        return s.replace("%", "\\%").replace("_", "\\_").replace("€", "EUR").replace("&", "\\&")

    # Column spec: metric label | ref value | (other value + Δ) per non-ref
    col_spec = "l" + "r" * (1 + 2 * len(_other_scens))

    # Header
    header_parts = [""]
    header_parts.append(f"\\textit{{{_ref_scen}}}")
    for s in _other_scens:
        header_parts += [f"\\textit{{{s}}}", "$\\Delta$"]
    header_line = " & ".join(header_parts) + " \\\\"

    # Data rows
    data_rows = []
    for metric, label in zip(summary.index, _metric_labels):
        unit = _units.get(metric, "")
        ref_val = summary.at[metric, _ref_scen]
        parts = [_tex_escape(f"{metric} ({unit})")]
        parts.append(_fmt_num(ref_val))
        for scen in _other_scens:
            other_val = summary.at[metric, scen] if scen in summary.columns else float("nan")
            delta_val = (
                pct_diff.at[label, scen]
                if label in pct_diff.index and scen in pct_diff.columns
                else float("nan")
            )
            parts.append(_fmt_num(other_val))
            parts.append(_fmt_pct(delta_val))
        data_rows.append("    " + " & ".join(parts) + " \\\\")

    latex_lines = [
        "\\clearpage",
        "\\begin{table}[htbp]",
        f"\\caption{{Scenario comparison: key metrics ({', '.join(str(c) for c in COUNTRIES)}, {', '.join(str(y) for y in YEARS)})}}",
        f"\\label{{tab:scenario\\_comparison\\_{'_'.join(str(c) for c in COUNTRIES)}}}",
        "\\small",
        f"\\begin{{tabular}}{{{col_spec}}}",
        "\\toprule",
        header_line,
        "\\midrule",
    ] + data_rows + [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]

    latex_table = "\n".join(latex_lines)
    latex_path = SDIR / f"{IDX_GROUP_NAME}_scenario_comparison.tex"
    latex_path.write_text(latex_table, encoding="utf-8")
    print(f"\nLaTeX table saved to: {latex_path}")
    print("\n" + latex_table)

Reference scenario: 'vestas3'

Percentage differences:

scenario                      low50
metric
Solar PV (GW)                 -18.4
Wind onshore (GW)             207.1
Solar PV (TWh)                -17.4
Wind onshore (TWh)            277.3
H2 Electrolysis (GW)          -19.5
H2 Tank (TWh)                 -68.0
System costs (bn €/yr)         -2.9
H2 export price (EUR/MWh_H2)   -1.8
HBI price (EUR/MWh_HBI)        -1.7

LaTeX table saved to: /mnt/data/gsa/pypsa-earth-custom-lukas/results/WSA_summary_v1/MA_MAIN_scenario_comparison.tex

\clearpage
\begin{table}[htbp]
\caption{Scenario comparison: key metrics (MA, 2050)}
\label{tab:scenario\_comparison\_MA}
\small
\begin{tabular}{lrrr}
\toprule
 & \textit{vestas3} & \textit{low50} & $\Delta$ \\
\midrule
    Solar PV (GW) & 414 & 338 & $-18\%$ \\
    Wind onshore (GW) & 14.1 & 43.3 & $+207\%$ \\
    Solar PV supply (TWh) & 651 & 538 & $-17\%$ \\
    Wind onshore supply (TWh) & 41.0 & 155 & $+277\%$ \\
    H2 Electrolysis (GW) & 39.4 & 31.7 & $-20\%$ \\
    H2 Tank (TWh) & 78.5 & 25.1 & $-68\%$ \\
    System costs (bn EUR/yr) & 44.2 & 42.9 & $-3\%$ \\
    H2 export price (EUR/MWh\_H2) & 170 & 166 & $-2\%$ \\
    HBI price (EUR/MWh\_HBI) & 691 & 679 & $-2\%$ \\
\bottomrule
\end{tabular}
\end{table}