Plot the summary of statistics (energy balance, optimal capacity, ...) 

**Prerequisites**

* Execute "make_stats_dict.py" before using this notebook. The script make_stats_dict creates csv for the metrics for all runs of multiple config files. 
* Install the environment envs/pypsa-earth-vis.yaml

In [971]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px

from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [972]:
def add_production_consumption_legend_groups(fig, df):
    """
    Add legend groups for Production (positive values) and Consumption (negative values).
    
    Parameters:
    -----------
    fig : plotly.graph_objects.Figure
        The plotly figure to modify
    df : pandas.DataFrame
        The dataframe containing the data with 'variable' and 'value' columns
    
    Returns:
    --------
    fig : plotly.graph_objects.Figure
        The modified figure with legend groups
    """
    # Add legend groups for Production (positive values) and Consumption (negative values)
    for trace in fig.data:
        # Get the variable name from the trace
        variable_name = trace.name
        
        # Check if this variable typically has positive or negative values in the data
        variable_data = df[df['variable'] == variable_name]['value']
        
        if len(variable_data) > 0:
            # Determine if this variable is primarily production (positive) or consumption (negative)
            avg_value = variable_data.mean()
            
            if avg_value > 0:
                trace.legendgroup = "Production"
                trace.legendgrouptitle = {"text": "Production"}
            else:
                trace.legendgroup = "Consumption" 
                trace.legendgrouptitle = {"text": "Consumption"}
    
    return fig

In [973]:
run_name_prefix = "DKS" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary"
sdir.mkdir(exist_ok=True, parents=True)

In [974]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "opts", "discountrate"] #, , "demand" "sopts"


for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_H2.csv
Imported oil from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_oil.csv
Imported gas from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_gas.csv
Imported co2 stored from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_co2 stored.csv
Imported co2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/balance_dict_co2.csv
Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/optimal_capacity_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/optimal_capacity_dict_H2.csv
Imported capex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/costs_dict_capex.csv
Imported opex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary/costs_dict_opex.csv

In [975]:
# def set_scen_col(df):
#     """
#     Set combined scenario str (for plots).
#     NB: This is specific to the experiment and should be adapted for other experiments.
#     """
#     df = df.copy()

#     df["scen"] = df["eopts"] + "+" + df["sopts"]
#     df = df.drop(columns=["eopts", "sopts"])
#     #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
#     #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

#     return df

def set_scen_col(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    scen = df["demand"].map({"RF": "AB", "EL": "AT"})
    # Add export info
    export_info = ""
    # Add export info based on 'eopts', handling NaN and string values
    export_info = df["eopts"].apply(
        lambda x: "50%Exp" if isinstance(x, str) and "v0.5" in x
        else ("NoExp" if pd.isna(x) or str(x) == "" else "100%Exp")
    )
    # Combine
    df["scen"] = scen + export_info.replace("", "", regex=False).apply(lambda x: f"+{x}" if x else "") + df["sopts"].replace("1H", "", regex=False)
    df = df.drop(columns=["eopts", "sopts", "demand"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

# Plotting

In [976]:
balance_dict["AC"]

                                                                                AC  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0         -33.7
                                                      NH3v0.5+FTv0.5         -33.7
                                                      NaN                    -33.7
                                               RF     NH3v1.0+FTv1.0         -30.1
                                                      NH3v0.5+FTv0.5         -30.1
                                                      NaN                    -30.1
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0         -53.8
                                                      NH3v0.5+FTv0.5         -53.8
                                                      NaN                    -53.8
                                               RF     NH3v1.0+FTv1.0         -61.4
                                                      NH3v0.5+FTv0.5         -61.4
                                                      NaN                    -61.4
                DKS_EG_2030 EG      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0 -153.5
                                                      H2v0.5+NH3v0.5+FTv0.5 -153.5
                                                      NaN                   -153.5
                                               RF     H2v1.0+NH3v1.0+FTv1.0 -166.9
                                                      H2v0.5+NH3v0.5+FTv0.5 -166.9
                                                      NaN                   -166.9
                DKS_EG_2050 EG      2050 1H    RF     H2v1.0+NH3v1.0+FTv1.0 -283.6
                                                      H2v0.5+NH3v0.5+FTv0.5 -283.6
                                                      NaN                   -283.6
                                               EL     H2v1.0+NH3v1.0+FTv1.0 -224.8
                                                      H2v0.5+NH3v0.5+FTv0.5 -224.8
                                                      NaN                   -224.8
                DKS_MA_2030 MA      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0  -37.7
                                                      H2v0.5+NH3v0.5+FTv0.5  -37.7
                                                      NaN                    -37.7
                                               RF     H2v1.0+NH3v1.0+FTv1.0  -39.9
                                                      H2v0.5+NH3v0.5+FTv0.5  -39.9
                                                      NaN                    -39.9
                DKS_MA_2050 MA      2050 1H    EL     H2v1.0+NH3v1.0+FTv1.0  -47.9
                                                      H2v0.5+NH3v0.5+FTv0.5  -47.9
                                                      NaN                    -47.9
                                               RF     H2v1.0+NH3v1.0+FTv1.0  -62.7
                                                      H2v0.5+NH3v0.5+FTv0.5  -62.7
                                                      NaN                    -62.7
                DKS_ZA_2030 ZA      2030 1H    EL     NH3v1.0+FTv1.0         -55.2
                                                      NH3v0.5+FTv0.5         -55.2
                                                      NaN                    -55.2
                                               RF     NH3v1.0+FTv1.0         -62.1
                                                      NH3v0.5+FTv0.5         -62.1
                                                      NaN                    -62.1
                DKS_ZA_2050 ZA      2050 1H    EL     NH3v1.0+FTv1.0         -75.3
                                                      NH3v0.5+FTv0.5         -75.3
                                                      NaN                    -75.3
                                               RF     NH3v1.0+FTv1.0        -105.8
                                                      NH3v0.5+FTv0.5        -105.8
                                                      NaN                   -105.8

                                                                             BEV charger  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0                -2.1
                                                      NH3v0.5+FTv0.5                -2.1
                                                      NaN                           -2.1
                                               RF     NH3v1.0+FTv1.0                -1.4
                                                      NH3v0.5+FTv0.5                -1.4
                                                      NaN                           -1.4
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0               -32.0
                                                      NH3v0.5+FTv0.5               -32.0
                                                      NaN                          -32.0
                                               RF     NH3v1.0+FTv1.0               -24.1
                                                      NH3v0.5+FTv0.5               -24.1
                                                      NaN                          -24.1
                DKS_EG_2030 EG      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0         -3.7
                                                      H2v0.5+NH3v0.5+FTv0.5         -3.7
                                                      NaN                           -3.7
                                               RF     H2v1.0+NH3v1.0+FTv1.0         -2.5
                                                      H2v0.5+NH3v0.5+FTv0.5         -2.5
                                                      NaN                           -2.5
                DKS_EG_2050 EG      2050 1H    RF     H2v1.0+NH3v1.0+FTv1.0        -50.7
                                                      H2v0.5+NH3v0.5+FTv0.5        -50.7
                                                      NaN                          -50.7
                                               EL     H2v1.0+NH3v1.0+FTv1.0        -63.2
                                                      H2v0.5+NH3v0.5+FTv0.5        -63.2
                                                      NaN                          -63.2
                DKS_MA_2030 MA      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0         -6.8
                                                      H2v0.5+NH3v0.5+FTv0.5         -6.8
                                                      NaN                           -6.8
                                               RF     H2v1.0+NH3v1.0+FTv1.0         -2.8
                                                      H2v0.5+NH3v0.5+FTv0.5         -2.8
                                                      NaN                           -2.8
                DKS_MA_2050 MA      2050 1H    EL     H2v1.0+NH3v1.0+FTv1.0        -46.7
                                                      H2v0.5+NH3v0.5+FTv0.5        -46.7
                                                      NaN                          -46.7
                                               RF     H2v1.0+NH3v1.0+FTv1.0        -31.8
                                                      H2v0.5+NH3v0.5+FTv0.5        -31.8
                                                      NaN                          -31.8
                DKS_ZA_2030 ZA      2030 1H    EL     NH3v1.0+FTv1.0                -5.0
                                                      NH3v0.5+FTv0.5                -5.0
                                                      NaN                           -5.0
                                               RF     NH3v1.0+FTv1.0                -3.4
                                                      NH3v0.5+FTv0.5                -3.4
                                                      NaN                           -3.4
                DKS_ZA_2050 ZA      2050 1H    EL     NH3v1.0+FTv1.0               -82.0
                                                      NH3v0.5+FTv0.5               -82.0
                                                      NaN                          -82.0
                                               RF     NH3v1.0+FTv1.0               -64.5
                                                      NH3v0.5+FTv0.5               -64.5
                                                      NaN                          -64.5

                                                                              CCGT  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0           1.7
                                                      NH3v0.5+FTv0.5           2.1
                                                      NaN                      5.1
                                               RF     NH3v1.0+FTv1.0           1.1
                                                      NH3v0.5+FTv0.5           1.6
                                                      NaN                      4.6
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0          11.7
                                                      NH3v0.5+FTv0.5          10.8
                                                      NaN                     10.5
                                               RF     NH3v1.0+FTv1.0           5.0
                                                      NH3v0.5+FTv0.5           5.1
                                                      NaN                      6.0
                DKS_EG_2030 EG      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0  232.2
                                                      H2v0.5+NH3v0.5+FTv0.5  204.3
                                                      NaN                    189.1
                                               RF     H2v1.0+NH3v1.0+FTv1.0  219.4
                                                      H2v0.5+NH3v0.5+FTv0.5  181.5
                                                      NaN                    168.0
                DKS_EG_2050 EG      2050 1H    RF     H2v1.0+NH3v1.0+FTv1.0    0.0
                                                      H2v0.5+NH3v0.5+FTv0.5    0.0
                                                      NaN                      0.0
                                               EL     H2v1.0+NH3v1.0+FTv1.0    0.0
                                                      H2v0.5+NH3v0.5+FTv0.5    0.0
                                                      NaN                      0.0
                DKS_MA_2030 MA      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0    2.7
                                                      H2v0.5+NH3v0.5+FTv0.5    3.6
                                                      NaN                      3.4
                                               RF     H2v1.0+NH3v1.0+FTv1.0   10.1
                                                      H2v0.5+NH3v0.5+FTv0.5   10.4
                                                      NaN                     11.4
                DKS_MA_2050 MA      2050 1H    EL     H2v1.0+NH3v1.0+FTv1.0    0.0
                                                      H2v0.5+NH3v0.5+FTv0.5    0.0
                                                      NaN                      0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0    0.0
                                                      H2v0.5+NH3v0.5+FTv0.5    0.0
                                                      NaN                      0.0
                DKS_ZA_2030 ZA      2030 1H    EL     NH3v1.0+FTv1.0           0.0
                                                      NH3v0.5+FTv0.5           0.0
                                                      NaN                     11.1
                                               RF     NH3v1.0+FTv1.0           0.0
                                                      NH3v0.5+FTv0.5           0.0
                                                      NaN                      0.0
                DKS_ZA_2050 ZA      2050 1H    EL     NH3v1.0+FTv1.0           0.0
                                                      NH3v0.5+FTv0.5           0.0
                                                      NaN                      0.0
                                               RF     NH3v1.0+FTv1.0           0.0
                                                      NH3v0.5+FTv0.5           0.0
                                                      NaN                      0.0

                                                                              DAC  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0         -0.0
                                                      NH3v0.5+FTv0.5         -0.0
                                                      NaN                    -0.0
                                               RF     NH3v1.0+FTv1.0         -0.0
                                                      NH3v0.5+FTv0.5         -0.0
                                                      NaN                    -0.0
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0         -6.5
                                                      NH3v0.5+FTv0.5         -4.7
                                                      NaN                    -2.7
                                               RF     NH3v1.0+FTv1.0         -7.9
                                                      NH3v0.5+FTv0.5         -5.4
                                                      NaN                    -2.7
                DKS_EG_2030 EG      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0  -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5  -0.0
                                                      NaN                    -0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0  -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5  -0.0
                                                      NaN                    -0.0
                DKS_EG_2050 EG      2050 1H    RF     H2v1.0+NH3v1.0+FTv1.0  -3.1
                                                      H2v0.5+NH3v0.5+FTv0.5  -2.5
                                                      NaN                    -2.2
                                               EL     H2v1.0+NH3v1.0+FTv1.0  -4.9
                                                      H2v0.5+NH3v0.5+FTv0.5  -4.2
                                                      NaN                    -4.0
                DKS_MA_2030 MA      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0  -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5  -0.0
                                                      NaN                    -0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0  -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5  -0.0
                                                      NaN                    -0.0
                DKS_MA_2050 MA      2050 1H    EL     H2v1.0+NH3v1.0+FTv1.0  -5.1
                                                      H2v0.5+NH3v0.5+FTv0.5  -1.7
                                                      NaN                    -0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0  -5.8
                                                      H2v0.5+NH3v0.5+FTv0.5  -5.5
                                                      NaN                    -2.7
                DKS_ZA_2030 ZA      2030 1H    EL     NH3v1.0+FTv1.0         -0.0
                                                      NH3v0.5+FTv0.5         -0.0
                                                      NaN                    -0.0
                                               RF     NH3v1.0+FTv1.0         -0.0
                                                      NH3v0.5+FTv0.5         -0.0
                                                      NaN                    -0.0
                DKS_ZA_2050 ZA      2050 1H    EL     NH3v1.0+FTv1.0        -10.9
                                                      NH3v0.5+FTv0.5         -9.5
                                                      NaN                    -6.2
                                               RF     NH3v1.0+FTv1.0         -4.2
                                                      NH3v0.5+FTv0.5         -3.4
                                                      NaN                    -2.7

                                                                             Fischer-Tropsch  \
run_name_prefix run_name    country year sopts demand eopts
DKS             DKS_CL_2030 CL      2030 1H    EL     NH3v1.0+FTv1.0                    -0.1
                                                      NH3v0.5+FTv0.5                    -0.0
                                                      NaN                               -0.0
                                               RF     NH3v1.0+FTv1.0                    -0.1
                                                      NH3v0.5+FTv0.5                    -0.0
                                                      NaN                               -0.0
                DKS_CL_2050 CL      2050 1H    EL     NH3v1.0+FTv1.0                    -1.0
                                                      NH3v0.5+FTv0.5                    -0.8
                                                      NaN                               -0.5
                                               RF     NH3v1.0+FTv1.0                    -1.4
                                                      NH3v0.5+FTv0.5                    -1.3
                                                      NaN                               -1.0
                DKS_EG_2030 EG      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0             -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.0
                                                      NaN                               -0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0             -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.0
                                                      NaN                               -0.0
                DKS_EG_2050 EG      2050 1H    RF     H2v1.0+NH3v1.0+FTv1.0             -1.0
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.9
                                                      NaN                               -0.8
                                               EL     H2v1.0+NH3v1.0+FTv1.0             -0.9
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.9
                                                      NaN                               -0.8
                DKS_MA_2030 MA      2030 1H    EL     H2v1.0+NH3v1.0+FTv1.0             -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.0
                                                      NaN                               -0.0
                                               RF     H2v1.0+NH3v1.0+FTv1.0             -0.0
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.0
                                                      NaN                               -0.0
                DKS_MA_2050 MA      2050 1H    EL     H2v1.0+NH3v1.0+FTv1.0             -0.6
                                                      H2v0.5+NH3v0.5+FTv0.5             -0.6
                                                      NaN                               -0.6

In [977]:
print(balance_dict["AC"].index.names)
print(balance_dict["AC"].index)

['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'demand', 'eopts']
MultiIndex([('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_CL_2030', 'CL', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_CL_2050', 'CL', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_EG_2050', 'EG', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_MA_2030', 'MA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_MA_2050', 'MA', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2030', 'ZA', 2030, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'EL', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'RF', ...),
            ('DKS', 'DKS_ZA_2050', 'ZA', 2050, '1H', 'RF', ...)],
           names=['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'demand', 'eopts'])

In [978]:
width = 800
heights = {"1": 300,"2": 500,"3": 600,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    # facet_row="run_name",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

scen_order = ["AB+50%Exp", "AT+100%Exp", "AT+50%Exp", "AT+NoExp"] # option to specify order of scenarios in the plot

In [979]:
# balance_dict["gas"].query("year == 2050 and country == 'ZA'").T

In [980]:
# balance_dict["co2 stored"].query("year == 2050 and country == 'ZA'").T

In [ ]:
# select and define index group (multiindex) for plots: which solutions to show at once

idx_group = idx_slice[["DKS"],:,["EG"],[2030, 2050],["1H"]]
idx_group_name = ""

print(idx_group_name) 
print(idx_group)

scen_filter = ["AB+50%Exp", "AT+100%Exp", "AT+50%Exp", "AT+NoExp"]

(['DKS'], slice(None, None, None), ['ZA'], [2030, 2050], ['1H'])

## Energy market balance | Electricity

In [982]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter")

supply_df = df[df["value"]>=0].copy()

In [983]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [984]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply in TWh<sub>el</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        # "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)

fig.show()

#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                       value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA        295.0
                            AT+100%Exp 2030 ZA        334.7
                            AT+50%Exp  2030 ZA        313.1
                            AT+NoExp   2030 ZA        291.3
                DKS_ZA_2050 AB+50%Exp  2050 ZA       1232.4
                            AT+100%Exp 2050 ZA       1262.7
                            AT+50%Exp  2050 ZA       1212.2
                            AT+NoExp   2050 ZA       1160.8

In [985]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand in TWh<sub>el</sub>","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                       value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA        295.0
                            AT+100%Exp 2030 ZA        334.8
                            AT+50%Exp  2030 ZA        313.0
                            AT+NoExp   2030 ZA        291.3
                DKS_ZA_2050 AB+50%Exp  2050 ZA       1232.5
                            AT+100%Exp 2050 ZA       1262.7
                            AT+50%Exp  2050 ZA       1212.3
                            AT+NoExp   2050 ZA       1160.9

## Energy and feedstock market balance | Hydrogen

In [986]:
df = prepare_dataframe(balance_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]!=0]
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [987]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance in TWh","year":"",
            "variable":"", 
            "scen": ""},

)

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA        16.9
                            AT+100%Exp 2030 ZA        36.1
                            AT+50%Exp  2030 ZA        23.0
                            AT+NoExp   2030 ZA         9.9
                DKS_ZA_2050 AB+50%Exp  2050 ZA       457.9
                            AT+100%Exp 2050 ZA       459.1
                            AT+50%Exp  2050 ZA       426.6
                            AT+NoExp   2050 ZA       395.0

In [988]:
df[["scen", "year", "variable", "value"]]

           scen  year         variable  value
12    AB+50%Exp  2030  H2 Electrolysis   13.1
15    AB+50%Exp  2030         Industry   -2.9
17    AB+50%Exp  2030       Navigation   -0.9
19    AB+50%Exp  2030     Power-to-NH3  -10.4
20    AB+50%Exp  2030  Power-to-liquid   -2.7
21    AB+50%Exp  2030              SMR    1.9
22    AB+50%Exp  2030           SMR CC    1.9
36   AT+100%Exp  2030  H2 Electrolysis   26.2
39   AT+100%Exp  2030         Industry   -7.6
41   AT+100%Exp  2030       Navigation   -2.3
43   AT+100%Exp  2030     Power-to-NH3  -20.8
44   AT+100%Exp  2030  Power-to-liquid   -5.4
45   AT+100%Exp  2030              SMR    6.0
46   AT+100%Exp  2030           SMR CC    3.9
48    AT+50%Exp  2030  H2 Electrolysis   13.1
51    AT+50%Exp  2030         Industry   -7.6
53    AT+50%Exp  2030       Navigation   -2.3
55    AT+50%Exp  2030     Power-to-NH3  -10.4
56    AT+50%Exp  2030  Power-to-liquid   -2.7
57    AT+50%Exp  2030              SMR    7.8
58    AT+50%Exp  2030           SMR CC    2.1
63     AT+NoExp  2030         Industry   -7.6
65     AT+NoExp  2030       Navigation   -2.3
69     AT+NoExp  2030              SMR    9.9
84    AB+50%Exp  2050  H2 Electrolysis  455.2
87    AB+50%Exp  2050         Industry  -27.6
88    AB+50%Exp  2050   Land transport  -19.2
89    AB+50%Exp  2050       Navigation  -16.2
90    AB+50%Exp  2050     Power-to-CH4  -42.1
91    AB+50%Exp  2050     Power-to-NH3  -17.5
92    AB+50%Exp  2050  Power-to-liquid -335.3
93    AB+50%Exp  2050              SMR    2.6
108  AT+100%Exp  2050  H2 Electrolysis  453.7
111  AT+100%Exp  2050         Industry  -51.0
112  AT+100%Exp  2050   Land transport  -26.3
113  AT+100%Exp  2050       Navigation  -22.2
114  AT+100%Exp  2050     Power-to-CH4  -24.5
115  AT+100%Exp  2050     Power-to-NH3  -34.9
116  AT+100%Exp  2050  Power-to-liquid -300.2
117  AT+100%Exp  2050              SMR    5.5
120   AT+50%Exp  2050  H2 Electrolysis  420.1
123   AT+50%Exp  2050         Industry  -51.0
124   AT+50%Exp  2050   Land transport  -26.3
125   AT+50%Exp  2050       Navigation  -22.2
126   AT+50%Exp  2050     Power-to-CH4  -26.9
127   AT+50%Exp  2050     Power-to-NH3  -17.5
128   AT+50%Exp  2050  Power-to-liquid -282.7
129   AT+50%Exp  2050              SMR    6.5
132    AT+NoExp  2050  H2 Electrolysis  387.3
135    AT+NoExp  2050         Industry  -51.0
136    AT+NoExp  2050   Land transport  -26.3
137    AT+NoExp  2050       Navigation  -22.2
138    AT+NoExp  2050     Power-to-CH4  -30.3
140    AT+NoExp  2050  Power-to-liquid -265.2
141    AT+NoExp  2050              SMR    7.7

## Energy and feedstock market balance | Liquid fuel

In [989]:
df = prepare_dataframe(balance_dict["oil"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_oil)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [990]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+100%Exp 2030 ZA       448.3
                            AB+50%Exp  2030 ZA       446.4
                            AB+NoExp   2030 ZA       444.4
                            AT+100%Exp 2030 ZA       415.2
                            AT+50%Exp  2030 ZA       413.3
                            AT+NoExp   2030 ZA       411.3
                DKS_ZA_2050 AB+100%Exp 2050 ZA       367.0
                            AB+50%Exp  2050 ZA       353.7
                            AB+NoExp   2050 ZA       340.3
                            AT+100%Exp 2050 ZA       229.1
                            AT+50%Exp  2050 ZA       215.8
                            AT+NoExp   2050 ZA       202.4

## Energy and feedstock market balance | CH4

In [991]:
df = prepare_dataframe(balance_dict["gas"], idx_group, set_scen_col, rename_function=rename_gas)
df = df[df["value"]!=0]
# df.variable = df.variable.map(rename_gas)

In [992]:
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [993]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+100%Exp 2030 ZA        42.5
                            AB+50%Exp  2030 ZA        42.2
                            AB+NoExp   2030 ZA        42.0
                            AT+100%Exp 2030 ZA        47.4
                            AT+50%Exp  2030 ZA        47.2
                            AT+NoExp   2030 ZA        66.1
                DKS_ZA_2050 AB+100%Exp 2050 ZA        37.2
                            AB+50%Exp  2050 ZA        38.1
                            AB+NoExp   2050 ZA        39.8
                            AT+100%Exp 2050 ZA        20.7
                            AT+50%Exp  2050 ZA        22.7
                            AT+NoExp   2050 ZA        25.3

## Energy and feedstock market balance | CO2

In [994]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group, set_scen_col)
df = df[df["value"]!=0]

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [995]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+100%Exp 2030 ZA         1.0
                            AB+50%Exp  2030 ZA         0.5
                            AT+100%Exp 2030 ZA         1.0
                            AT+50%Exp  2030 ZA         0.6
                DKS_ZA_2050 AB+100%Exp 2050 ZA        83.0
                            AB+50%Exp  2050 ZA        79.7
                            AB+NoExp   2050 ZA        76.5
                            AT+100%Exp 2050 ZA       105.1
                            AT+50%Exp  2050 ZA       102.1
                            AT+NoExp   2050 ZA        99.0

## CO2 atmosphere balance

In [996]:
df = prepare_dataframe(balance_dict["co2"], idx_group, set_scen_col)

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [997]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions in Mt<sub>CO2</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+100%Exp 2030 ZA       282.6
                            AB+50%Exp  2030 ZA       282.8
                            AB+NoExp   2030 ZA       282.7
                            AT+100%Exp 2030 ZA       210.9
                            AT+50%Exp  2030 ZA       210.9
                            AT+NoExp   2030 ZA       210.9
                DKS_ZA_2050 AB+100%Exp 2050 ZA       115.2
                            AB+50%Exp  2050 ZA       112.1
                            AB+NoExp   2050 ZA       109.5
                            AT+100%Exp 2050 ZA        67.1
                            AT+50%Exp  2050 ZA        64.0
                            AT+NoExp   2050 ZA        61.1

In [998]:
1e4

10000.0

In [1015]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter")
df.variable = df.variable.map(rename_to_upper_case)
df = df[~((df["variable"] == "Coal") & (df["year"] == 2050))]
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [1016]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity in GW<sub>el</sub>","year":"",
            "variable":"",
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA       114.1
                            AT+100%Exp 2030 ZA       148.6
                            AT+50%Exp  2030 ZA       140.8
                            AT+NoExp   2030 ZA       135.4
                DKS_ZA_2050 AB+50%Exp  2050 ZA       601.0
                            AT+100%Exp 2050 ZA       610.8
                            AT+50%Exp  2050 ZA       594.3
                            AT+NoExp   2050 ZA       573.2

In [1009]:
df[["scen", "year", "variable", "value"]]

           scen  year      variable  value
13    AB+50%Exp  2030          Coal   40.0
15    AB+50%Exp  2030         Hydro    3.7
16    AB+50%Exp  2030       Nuclear    2.0
17    AB+50%Exp  2030      Solar PV   31.0
20    AB+50%Exp  2030           Oil    0.4
21    AB+50%Exp  2030  Wind onshore   37.0
35   AT+100%Exp  2030          Coal   40.0
37   AT+100%Exp  2030         Hydro    3.7
38   AT+100%Exp  2030       Nuclear    2.0
39   AT+100%Exp  2030      Solar PV   39.1
42   AT+100%Exp  2030           Oil    0.4
43   AT+100%Exp  2030  Wind onshore   63.4
46    AT+50%Exp  2030          Coal   40.0
48    AT+50%Exp  2030         Hydro    3.7
49    AT+50%Exp  2030       Nuclear    2.0
50    AT+50%Exp  2030      Solar PV   36.0
53    AT+50%Exp  2030           Oil    0.4
54    AT+50%Exp  2030  Wind onshore   58.7
57     AT+NoExp  2030          Coal   40.0
58     AT+NoExp  2030  Gas turbines    2.4
59     AT+NoExp  2030         Hydro    3.7
60     AT+NoExp  2030       Nuclear    2.0
61     AT+NoExp  2030      Solar PV   32.3
64     AT+NoExp  2030           Oil    0.4
65     AT+NoExp  2030  Wind onshore   54.6
77    AB+50%Exp  2050       Battery   32.9
79    AB+50%Exp  2050          Coal   40.0
80    AB+50%Exp  2050  Gas turbines    2.3
81    AB+50%Exp  2050         Hydro    3.7
82    AB+50%Exp  2050       Nuclear    2.0
83    AB+50%Exp  2050      Solar PV  346.9
86    AB+50%Exp  2050           Oil    0.4
87    AB+50%Exp  2050  Wind onshore  212.8
99   AT+100%Exp  2050       Battery   33.7
101  AT+100%Exp  2050          Coal   40.0
102  AT+100%Exp  2050  Gas turbines    6.0
103  AT+100%Exp  2050         Hydro    3.7
104  AT+100%Exp  2050       Nuclear    2.0
105  AT+100%Exp  2050      Solar PV  352.3
108  AT+100%Exp  2050           Oil    0.4
109  AT+100%Exp  2050  Wind onshore  212.7
110   AT+50%Exp  2050       Battery   35.4
112   AT+50%Exp  2050          Coal   40.0
113   AT+50%Exp  2050  Gas turbines    6.3
114   AT+50%Exp  2050         Hydro    3.7
115   AT+50%Exp  2050       Nuclear    2.0
116   AT+50%Exp  2050      Solar PV  345.2
119   AT+50%Exp  2050           Oil    0.4
120   AT+50%Exp  2050  Wind onshore  201.3
121    AT+NoExp  2050       Battery   35.5
123    AT+NoExp  2050          Coal   40.0
124    AT+NoExp  2050  Gas turbines    7.6
125    AT+NoExp  2050         Hydro    3.7
126    AT+NoExp  2050       Nuclear    2.0
127    AT+NoExp  2050      Solar PV  333.4
130    AT+NoExp  2050           Oil    0.4
131    AT+NoExp  2050  Wind onshore  190.6

In [1012]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [1013]:
fig_name = "hydrogen_installed_capacity_GW"
fig_kwargs_mod = fig_kwargs.copy()
fig_kwargs_mod["height"] = heights["2"]
fig = px.bar(
    df, 
    **fig_kwargs_mod,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity in GW<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA         1.9
                            AT+100%Exp 2030 ZA         6.9
                            AT+50%Exp  2030 ZA         5.2
                            AT+NoExp   2030 ZA         1.1
                DKS_ZA_2050 AB+50%Exp  2050 ZA        86.8
                            AT+100%Exp 2050 ZA        88.8
                            AT+50%Exp  2050 ZA        83.6
                            AT+NoExp   2050 ZA        78.4

In [1014]:
print(df[["scen", "year", "variable", "value"]])

          scen  year         variable  value
4    AB+50%Exp  2030  H2 Electrolysis    1.5
5    AB+50%Exp  2030              SMR    0.2
6    AB+50%Exp  2030           SMR CC    0.2
12  AT+100%Exp  2030  H2 Electrolysis    5.4
13  AT+100%Exp  2030              SMR    1.0
14  AT+100%Exp  2030           SMR CC    0.5
16   AT+50%Exp  2030  H2 Electrolysis    3.5
17   AT+50%Exp  2030              SMR    1.4
18   AT+50%Exp  2030           SMR CC    0.3
21    AT+NoExp  2030              SMR    1.1
28   AB+50%Exp  2050  H2 Electrolysis   81.2
29   AB+50%Exp  2050              SMR    5.6
36  AT+100%Exp  2050  H2 Electrolysis   80.1
37  AT+100%Exp  2050              SMR    8.7
40   AT+50%Exp  2050  H2 Electrolysis   74.3
41   AT+50%Exp  2050              SMR    9.3
44    AT+NoExp  2050  H2 Electrolysis   68.6
45    AT+NoExp  2050              SMR    9.8

In [1005]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group, set_scen_col)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [1006]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs["height"] = heights["3"]
fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        #"scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:                                                       value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AB+50%Exp  2030 ZA       4501.9
                            AT+100%Exp 2030 ZA       4506.9
                            AT+50%Exp  2030 ZA       4505.2
                            AT+NoExp   2030 ZA       4501.1
                DKS_ZA_2050 AB+50%Exp  2050 ZA       4586.8
                            AT+100%Exp 2050 ZA       4588.8
                            AT+50%Exp  2050 ZA       4583.6
                            AT+NoExp   2050 ZA       4578.4

## Relative costs

costs / total energy consumption

## Water consumption