Plot the summary of statistics (energy balance, optimal capacity, ...) 

**Prerequisites**

* Execute "make_stats_dict.py" before using this notebook. The script make_stats_dict creates csv for the metrics for all runs of multiple config files. 
* Install the environment envs/pypsa-earth-vis.yaml

In [623]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px

from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [624]:
def add_production_consumption_legend_groups(fig, df):
    """
    Add legend groups for Production (positive values) and Consumption (negative values).
    
    Parameters:
    -----------
    fig : plotly.graph_objects.Figure
        The plotly figure to modify
    df : pandas.DataFrame
        The dataframe containing the data with 'variable' and 'value' columns
    
    Returns:
    --------
    fig : plotly.graph_objects.Figure
        The modified figure with legend groups
    """
    # Add legend groups for Production (positive values) and Consumption (negative values)
    for trace in fig.data:
        # Get the variable name from the trace
        variable_name = trace.name
        
        # Check if this variable typically has positive or negative values in the data
        variable_data = df[df['variable'] == variable_name]['value']
        
        if len(variable_data) > 0:
            # Determine if this variable is primarily production (positive) or consumption (negative)
            avg_value = variable_data.mean()
            
            if avg_value > 0:
                trace.legendgroup = "Production"
                trace.legendgrouptitle = {"text": "Production"}
            else:
                trace.legendgroup = "Consumption" 
                trace.legendgrouptitle = {"text": "Consumption"}
    
    return fig

In [625]:
run_name_prefix = "DKS" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}v1_summary"
sdir.mkdir(exist_ok=True, parents=True)

In [626]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "opts", "discountrate"] #, , "demand" "sopts"


for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_H2.csv
Imported oil from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_oil.csv
Imported gas from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_gas.csv
Imported co2 stored from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_co2 stored.csv
Imported co2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\balance_dict_co2.csv
Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\optimal_capacity_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\optimal_capacity_dict_H2.csv
Imported capex from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\costs_dict_capex.csv
Imported opex from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKSv1_summary\costs_dict_opex.csv

In [627]:
# def set_scen_col(df):
#     """
#     Set combined scenario str (for plots).
#     NB: This is specific to the experiment and should be adapted for other experiments.
#     """
#     df = df.copy()

#     df["scen"] = df["eopts"] + "+" + df["sopts"]
#     df = df.drop(columns=["eopts", "sopts"])
#     #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
#     #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

#     return df

def set_scen_col(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    scen = df["demand"].map({"RF": "AB", "EL": "AT"})
    # Add export info
    export_info = ""
    # Add export info based on 'eopts', handling NaN and string values
    export_info = df["eopts"].apply(
        lambda x: "50%Exp" if isinstance(x, str) and "v0.5" in x
        else ("NoExp" if pd.isna(x) or str(x) == "" else "100%Exp")
    )
    # Combine
    df["scen"] = scen + export_info.replace("", "", regex=False).apply(lambda x: f"+{x}" if x else "") + df["sopts"].replace("144H", "", regex=False)
    df = df.drop(columns=["eopts", "sopts", "demand"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

# Plotting

In [628]:
print(balance_dict["AC"].index.names)
print(balance_dict["AC"].index)

['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'demand', 'eopts']
MultiIndex([('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'RF', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'EL', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'EL', ...),
            ('DKS', 'DKS_EG_2030', 'EG', 2030, '144H', 'EL', ...)],
           names=['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'demand', 'eopts'])

In [629]:
width = 700
heights = {"1": 300,"2": 600,"3": 700,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    # facet_row="run_name",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

scen_order = ["AB+50%Exp", "AB+100%Exp", "AT+50%Exp", "AT+NoExp"] # option to specify order of scenarios in the plot

In [630]:
# balance_dict["gas"].query("year == 2050 and country == 'ZA'").T

In [631]:
# balance_dict["co2 stored"].query("year == 2050 and country == 'ZA'").T

In [632]:
# select and define index group (multiindex) for plots: which solutions to show at once

idx_group = idx_slice[["DKS"],:,["EG"],[2030],["144H"]]
idx_group_name = ""

print(idx_group_name) 
print(idx_group)

scen_filter = ["AB+50%Exp", "AB+100%Exp", "AT+50%Exp", "AT+NoExp"]

(['DKS'], slice(None, None, None), ['EG'], [2030], ['144H'])

## Energy market balance | Electricity

In [633]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [634]:
df.scen.unique()

array(['AB+100%Exp', 'AB+50%Exp', 'AT+50%Exp', 'AT+NoExp'], dtype=object)

In [635]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply in TWh<sub>el</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)

fig.show()

#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       391.1
                            AB+50%Exp  2030 EG       352.3
                            AT+50%Exp  2030 EG       372.4
                            AT+NoExp   2030 EG       333.6

In [636]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand in TWh<sub>el</sub>","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       391.3
                            AB+50%Exp  2030 EG       352.4
                            AT+50%Exp  2030 EG       372.5
                            AT+NoExp   2030 EG       333.7

## Energy and feedstock market balance | Hydrogen

In [637]:
df = prepare_dataframe(balance_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]!=0]
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [638]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
0,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,Ammonia synthesis,-37.4
1,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,H2 Electrolysis,46.9
3,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,H2 export,-4.7
4,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,Industry,-7.8
6,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,Power-to-liquid,-4.8
7,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,SMR,4.4
8,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,SMR CC,3.6
9,DKS,DKS_EG_2030,AB+100%Exp,2030,EG,Shipping,-0.2
11,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,Ammonia synthesis,-18.7
12,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,H2 Electrolysis,23.4
14,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,H2 export,-2.4
15,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,Industry,-7.8
17,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,Power-to-liquid,-2.4
18,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,SMR,6.2
19,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,SMR CC,1.8
20,DKS,DKS_EG_2030,AB+50%Exp,2030,EG,Shipping,-0.2
44,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,Ammonia synthesis,-18.7
45,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,H2 Electrolysis,23.4
47,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,H2 export,-2.3
48,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,Industry,-14.0
50,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,Power-to-liquid,-2.4
51,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,SMR,12.6
52,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,SMR CC,1.8
53,DKS,DKS_EG_2030,AT+50%Exp,2030,EG,Shipping,-0.4
59,DKS,DKS_EG_2030,AT+NoExp,2030,EG,Industry,-14.0
62,DKS,DKS_EG_2030,AT+NoExp,2030,EG,SMR,14.4
64,DKS,DKS_EG_2030,AT+NoExp,2030,EG,Shipping,-0.4

In [639]:
supply_sum_df

                                                     value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG        54.9
                            AB+50%Exp  2030 EG        31.4
                            AT+50%Exp  2030 EG        37.8
                            AT+NoExp   2030 EG        14.4

In [640]:
demand_sum_df

                                                     value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG        54.9
                            AB+50%Exp  2030 EG        31.5
                            AT+50%Exp  2030 EG        37.8
                            AT+NoExp   2030 EG        14.4

In [641]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance in TWh","year":"",
            "variable":"", 
            "scen": ""},

)

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG        54.9
                            AB+50%Exp  2030 EG        31.5
                            AT+50%Exp  2030 EG        37.8
                            AT+NoExp   2030 EG        14.4

## Energy and feedstock market balance | Liquid fuel

In [642]:
df = prepare_dataframe(balance_dict["oil"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_oil)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [643]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       319.0
                            AB+50%Exp  2030 EG       317.3
                            AB+NoExp   2030 EG       315.5
                            AT+100%Exp 2030 EG       281.0
                            AT+50%Exp  2030 EG       279.3
                            AT+NoExp   2030 EG       277.5

## Energy and feedstock market balance | CH4

In [644]:
df = prepare_dataframe(balance_dict["gas"], idx_group, set_scen_col, rename_function=rename_gas)
df = df[df["value"]!=0]
# df.variable = df.variable.map(rename_gas)

In [645]:
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [646]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       227.9
                            AB+50%Exp  2030 EG       213.9
                            AB+NoExp   2030 EG       188.4
                            AT+100%Exp 2030 EG       219.2
                            AT+50%Exp  2030 EG       204.0
                            AT+NoExp   2030 EG       187.9

## Energy and feedstock market balance | CO2

In [647]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group, set_scen_col)
df = df[df["value"]!=0]

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [648]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG         0.9
                            AB+50%Exp  2030 EG         0.4
                            AT+100%Exp 2030 EG         0.9
                            AT+50%Exp  2030 EG         0.4

## CO2 atmosphere balance

In [649]:
df = prepare_dataframe(balance_dict["co2"], idx_group, set_scen_col)

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [650]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions in Mt<sub>CO2</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       182.6
                            AB+50%Exp  2030 EG       179.9
                            AB+NoExp   2030 EG       175.2
                            AT+100%Exp 2030 EG       171.0
                            AT+50%Exp  2030 EG       168.1
                            AT+NoExp   2030 EG       165.2

In [651]:
1e4

10000.0

In [652]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group, set_scen_col)
df = df[df["value"]<1e4] #drop loadshedding capacity
df.variable = df.variable.map(rename_electricity).map(rename_to_upper_case)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [653]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity in GW<sub>el</sub>","year":"",
            #"variable":"",
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       207.6
                            AB+50%Exp  2030 EG       185.4
                            AB+NoExp   2030 EG       167.4
                            AT+100%Exp 2030 EG       218.8
                            AT+50%Exp  2030 EG       197.2
                            AT+NoExp   2030 EG       175.1

In [654]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group, set_scen_col)
df = df[df["value"]<1e6] #drop loadshedding capacity
df.variable = df.variable.map(rename_h2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [655]:
fig_name = "hydrogen_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity in GW<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                        value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       13506.4
                            AB+50%Exp  2030 EG       13503.6
                            AB+NoExp   2030 EG       13500.9
                            AT+100%Exp 2030 EG       13507.2
                            AT+50%Exp  2030 EG       13504.4
                            AT+NoExp   2030 EG       13501.6

In [656]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group, set_scen_col)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [657]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs["height"] = heights["3"]
fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        #"scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:                                                        value
run_name_prefix run_name    scen       year country
DKS             DKS_EG_2030 AB+100%Exp 2030 EG       13506.4
                            AB+50%Exp  2030 EG       13503.6
                            AB+NoExp   2030 EG       13500.9
                            AT+100%Exp 2030 EG       13507.2
                            AT+50%Exp  2030 EG       13504.4
                            AT+NoExp   2030 EG       13501.6

## Relative costs

costs / total energy consumption

## Water consumption