Create summary of statistics (energy balance, optimal capacity, ...) of all runs of multiple config files - independent of Snakemake file.

In [36]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px
import plotly.graph_objects as go


from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [37]:
run_name_prefix = "H2G_B" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary_20250522"
sdir.mkdir(exist_ok=True, parents=True)

In [38]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])
mean_marginal_prices = read_stats_dict("mean_marginal_prices", sdir, keys=["H2 export bus"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "opts", "sopts", "discountrate", "demand"]

for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_H2.csv
Imported oil from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_oil.csv
Imported gas from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_gas.csv
Imported co2 stored from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_co2 stored.csv
Imported co2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\balance_dict_co2.csv
Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\optimal_capacity_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\optimal_capacity_dict_H2.csv
Imported capex from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\costs_dict_capex.csv
Imported opex from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\costs_dict_opex.csv
Imported H2 export bus from C:\Users\ljansen\projects\pypsa-earth-custom\results\H2G_B_summary_20250522\mean_marginal_prices_H2 export bus.csv

# Plotting

In [39]:
print(balance_dict["AC"].index.names)
print(balance_dict["AC"].index)

['run_name_prefix', 'country', 'year', 'h2export']
MultiIndex([('H2G_B', 'MA', 2030, 10.0)],
           names=['run_name_prefix', 'country', 'year', 'h2export'])

In [40]:
# select and define index group (multiindex) for plots: which solutions to show at once

idx_group = idx_slice[["H2G_B"],["MA"],[2030],:]
idx_group_name = ""

print(idx_group_name) 
print(idx_group)

(['H2G_B'], ['MA'], [2030], slice(None, None, None))

In [41]:
width = 700
heights = {"1": 300,"2": 600,"3": 700,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    facet_row="country",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

scen_order = [] # option to specify order of scenarios in the plot

## Energy market balance | Electricity

In [42]:
df = prepare_dataframe(balance_dict["AC"], idx_group)

df.variable = df.variable.map(rename_electricity).map(rename_to_upper_case)

# supply_df = df[df["value"]>=0.01].copy()
# supply_df = supply_df.groupby(["scen","year","variable"], as_index=False).sum()
# #supply_df = supply_df.query("variable not in ['Battery', 'Hydro Power']")
# supply_sums_df = supply_df.groupby(["scen","year"]).sum(numeric_only=True).round(0)
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [43]:
df

   run_name_prefix           scen  year country           variable  value
0            H2G_B  0.3MtH2export  2030      MA              Other  -45.8
1            H2G_B  0.3MtH2export  2030      MA  Electric vehicles   -1.8
2            H2G_B  0.3MtH2export  2030      MA       Gas turbines   12.0
9            H2G_B  0.3MtH2export  2030      MA        Agriculture   -4.1
10           H2G_B  0.3MtH2export  2030      MA            Battery   -0.6
11           H2G_B  0.3MtH2export  2030      MA            Battery    0.6
13           H2G_B  0.3MtH2export  2030      MA               Coal    1.5
14           H2G_B  0.3MtH2export  2030      MA              Hydro    2.4
15           H2G_B  0.3MtH2export  2030      MA           Industry  -16.9
18           H2G_B  0.3MtH2export  2030      MA                Oil    4.0
19           H2G_B  0.3MtH2export  2030      MA       Wind onshore   47.2
20           H2G_B  0.3MtH2export  2030      MA     Rail transport   -0.3
21           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -0.3
22           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -0.9
23           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -0.6
24           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -1.7
25           H2G_B  0.3MtH2export  2030      MA              Hydro    0.1
26           H2G_B  0.3MtH2export  2030      MA           Commerce   -8.5
31           H2G_B  0.3MtH2export  2030      MA           Solar PV   14.4
32           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -0.1
35           H2G_B  0.3MtH2export  2030      MA      Power-to-heat   -0.6

In [44]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply in TWh<sub>el</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        82.2

In [45]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand in TWh<sub>el</sub>","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        82.2

## Energy and feedstock market balance | Hydrogen

In [46]:
df = prepare_dataframe(balance_dict["H2"], idx_group)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_h2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [47]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance in TWh","year":"",
            "variable":"", 
            "scen": ""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        11.7

## Energy and feedstock market balance | Liquid fuel

In [48]:
df = prepare_dataframe(balance_dict["oil"], idx_group)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_oil)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [49]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA       158.2

## Energy and feedstock market balance | CH4

In [50]:
df = prepare_dataframe(balance_dict["gas"], idx_group)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_gas)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [51]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        44.6

## Energy and feedstock market balance | CO2

In [52]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group)
df = df[df["value"]!=0]

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [53]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        19.1

## CO2 atmosphere balance

In [54]:
balance_dict.keys()

dict_keys(['AC', 'H2', 'oil', 'gas', 'co2 stored', 'co2'])

In [55]:
df = prepare_dataframe(balance_dict["co2"], idx_group)

#df.variable = df.variable.map(rename_co2)

# supply_df = df[df["value"]>=0.01].copy()
# supply_df = supply_df.groupby(["scen","year","variable"], as_index=False).sum()
# #supply_df = supply_df.query("variable not in ['Battery', 'Hydro Power']")
# supply_sums_df = supply_df.groupby(["scen","year"]).sum(numeric_only=True).round(0)
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [56]:
df

,run_name_prefix,scen,year,country,variable,value
0,H2G_B,0.3MtH2export,2030,MA,CCGT,4.1
4,H2G_B,0.3MtH2export,2030,MA,SMR CC,0.3
6,H2G_B,0.3MtH2export,2030,MA,co2,-53.0
8,H2G_B,0.3MtH2export,2030,MA,coal,1.6
9,H2G_B,0.3MtH2export,2030,MA,gas for industry,0.3
11,H2G_B,0.3MtH2export,2030,MA,industry coal emissions,0.1
12,H2G_B,0.3MtH2export,2030,MA,industry oil emissions,8.3
13,H2G_B,0.3MtH2export,2030,MA,land transport oil emissions,15.5
14,H2G_B,0.3MtH2export,2030,MA,oil,2.9
15,H2G_B,0.3MtH2export,2030,MA,oil emissions,16.0
16,H2G_B,0.3MtH2export,2030,MA,process emissions,0.1
17,H2G_B,0.3MtH2export,2030,MA,process emissions CC,1.8
18,H2G_B,0.3MtH2export,2030,MA,residential rural gas boiler,0.3
19,H2G_B,0.3MtH2export,2030,MA,residential urban decentral gas boiler,0.7
22,H2G_B,0.3MtH2export,2030,MA,shipping oil emissions,0.8
26,H2G_B,0.3MtH2export,2030,MA,urban central gas boiler,0.1

In [57]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions in Mt<sub>CO2</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        52.9

## Installed Capacities | Electricity

In [58]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group)
df = df[df["value"]<1e6] #drop loadshedding capacity
df.variable = df.variable.map(rename_electricity).map(rename_to_upper_case)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [59]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity in GW<sub>el</sub>","year":"",
            #"variable":"",
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA        42.6

In [60]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group)
df = df[df["value"]<1e6] #drop loadshedding capacity
df.variable = df.variable.map(rename_h2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [61]:
fig_name = "hydrogen_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity in GW<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA         1.3

In [62]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [63]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs["height"] = heights["3"]
fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        #"scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:                             value
scen          year country
0.3MtH2export 2030 MA         1.3

## Relative costs

costs / total energy consumption

## Water consumption

## Marginal prices | H2 export price

In [64]:
print(mean_marginal_prices["H2 export bus"])

                                                                                                  H2 export bus
run_name_prefix country year simpl clusters ll   opts     sopts discountrate demand     h2export
H2G_B           MA      2030 NaN   3flex    copt Co2L0.83 3h    0.071        MA-GNZ-IEE 10.0           52.69488

In [65]:
df = prepare_dataframe(
    mean_marginal_prices["H2 export bus"], 
    idx_slice[["H2G_A"],:,[2035],:]
)

df = df.query("variable in ['H2 export bus']")

KeyError: 'H2G_A'

In [ ]:
def marginal_price_dumbbell_fig(df, year):

    df = df.copy()
    df = df[df.year==year]
    countries = df.sort_values(by=["value"], ascending=False)["country"]

    data = {"line_x": [], "line_y": [], "0.1MtH2export": [], "0.7MtH2export": [], "colors": [], "years": [], "countries": []}

    for country in countries:
        data["0.1MtH2export"].extend([df.loc[(df.scen == "0.1MtH2export") & (df.country == country)]["value"].values[0]])
        data["0.7MtH2export"].extend([df.loc[(df.scen == "0.7MtH2export") & (df.country == country)]["value"].values[0]])
        data["line_x"].extend(
            [
                df.loc[(df.scen == "0.1MtH2export") & (df.country == country)]["value"].values[0],
                df.loc[(df.scen == "0.7MtH2export") & (df.country == country)]["value"].values[0],
                None,
            ]
        )
        data["line_y"].extend([country, country, None]),

    fig = go.Figure(
        data=[
            go.Scatter(
                x=data["line_x"],
                y=data["line_y"],
                mode="lines",
                showlegend=False,
                marker=dict(
                    color="grey"
                )
            ),
            go.Scatter(
                x=data["0.1MtH2export"],
                y=countries,
                mode="markers+text",
                name="0.1MtH2export",
                text=data["0.1MtH2export"],            
                textposition="top center",
                texttemplate="%{text:.1f}",
                textfont=dict(size=11),
                marker=dict(
                    color="#A6BCC9",
                    size=13
                )

            ),
            go.Scatter(
                x=data["0.7MtH2export"],
                y=countries,
                mode="markers+text",
                name="0.7MtH2export",
                text=data["0.7MtH2export"],
                textposition="top center",
                texttemplate="%{text:.1f}",
                textfont=dict(size=11),
                marker=dict(
                    color="#179c7d",
                    size=13
                )
            ),
        ]
    )

    fig.update_layout(
        title=dict(text=nice_title(f"Marginal price for H2 at export port in {year}", 
                                   "Per country and H2 export volume in €/MWh_H2_LHV")),
        width=800,
        height=500,
        legend_itemclick=False
    )
    return fig

fig = marginal_price_dumbbell_fig(df, year=2035)

fig.show()

In [ ]:

fig = marginal_price_dumbbell_fig(df, year=2050)

fig.show()