Plot the summary of statistics (energy balance, optimal capacity, ...) 

**Prerequisites**

* Execute "make_stats_dict.py" before using this notebook. The script make_stats_dict creates csv for the metrics for all runs of multiple config files. 
* Install the environment envs/pypsa-earth-vis.yaml

In [324]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px

from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Navigation

### Main Sections
[⬇️ Go to Plotting](#plotting)
- [⬇️ Energy market balance | Electricity](#energy-market-balance--electricity)
- [⬇️ Energy and feedstock market balance | Hydrogen](#energy-and-feedstock-market-balance--hydrogen)
- [⬇️ Energy and feedstock market balance | Liquid fuel](#energy-and-feedstock-market-balance--liquid-fuel)
- [⬇️ Energy and feedstock market balance | CH4](#energy-and-feedstock-market-balance--ch4)
- [⬇️ Energy and feedstock market balance | CO2](#energy-and-feedstock-market-balance--co2)
- [⬇️ CO2 atmosphere balance](#co2-atmosphere-balance)

[⬇️ Go to Installed Capacity](#installed-capacity)

[⬇️ Go to Relative costs](#relative-costs)

[⬇️ Go to Water consumption](#water-consumption)

In [325]:
def add_production_consumption_legend_groups(fig, df):
    """
    Add legend groups for Production (positive values) and Consumption (negative values).
    
    Parameters:
    -----------
    fig : plotly.graph_objects.Figure
        The plotly figure to modify
    df : pandas.DataFrame
        The dataframe containing the data with 'variable' and 'value' columns
    
    Returns:
    --------
    fig : plotly.graph_objects.Figure
        The modified figure with legend groups
    """
    # Add legend groups for Production (positive values) and Consumption (negative values)
    for trace in fig.data:
        # Get the variable name from the trace
        variable_name = trace.name
        
        # Check if this variable typically has positive or negative values in the data
        variable_data = df[df['variable'] == variable_name]['value']
        
        if len(variable_data) > 0:
            # Determine if this variable is primarily production (positive) or consumption (negative)
            avg_value = variable_data.mean()
            
            if avg_value > 0:
                trace.legendgroup = "Production"
                trace.legendgrouptitle = {"text": "Production"}
            else:
                trace.legendgroup = "Consumption" 
                trace.legendgrouptitle = {"text": "Consumption"}
    
    return fig

In [326]:
run_name_prefix = "DKS" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary_202508"
sdir.mkdir(exist_ok=True, parents=True)

In [327]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "opts", "discountrate"] #, , "demand" "sopts"


for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_H2.csv
Imported oil from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_oil.csv
Imported gas from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_gas.csv
Imported co2 stored from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_co2 stored.csv
Imported co2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/balance_dict_co2.csv
Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/optimal_capacity_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/optimal_capacity_dict_H2.csv
Imported capex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/costs_dict_capex.csv
Imported opex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/DKS_summary_202508/costs_dict_opex.csv

In [328]:
# def set_scen_col(df):
#     """
#     Set combined scenario str (for plots).
#     NB: This is specific to the experiment and should be adapted for other experiments.
#     """
#     df = df.copy()

#     df["scen"] = df["eopts"] + "+" + df["sopts"]
#     df = df.drop(columns=["eopts", "sopts"])
#     #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
#     #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

#     return df

def set_scen_col(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    scen = df["demand"].map({"RF": "AB", "EL": "AT"})
    # Add export info
    export_info = ""
    # Add export info based on 'eopts', handling NaN and string values
    export_info = df["eopts"].apply(
        lambda x: "50%Exp" if isinstance(x, str) and "v0.5" in x
        else ("NoExp" if pd.isna(x) or str(x) == "" else "100%Exp")
    )
    # Combine
    df["scen"] = scen + export_info.replace("", "", regex=False).apply(lambda x: f"+{x}" if x else "") + df["sopts"].replace("1H", "", regex=False)
    df = df.drop(columns=["eopts", "sopts", "demand"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

# Plotting

In [329]:
# select and define index group (multiindex) for plots: which solutions to show at once

idx_group = idx_slice[["DKS"],:,["ZA"],[2030, 2050],["1H"]]
idx_group_name = ""

print(idx_group_name) 
print(idx_group)

scen_filter = ["AB+50%Exp", "AT+100%Exp", "AT+50%Exp", "AT+NoExp"]

(['DKS'], slice(None, None, None), ['ZA'], [2030, 2050], ['1H'])

In [330]:
print(balance_dict["AC"].index.names)
# print(balance_dict["AC"].index)

['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'demand', 'eopts']

In [331]:
width = 800
heights = {"1": 300,"2": 500,"3": 600,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    # facet_row="run_name",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

scen_order = ["AB+50%Exp", "AT+100%Exp", "AT+50%Exp", "AT+NoExp"] # option to specify order of scenarios in the plot

## Energy market balance | Electricity

In [332]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter")

supply_df = df[df["value"]>=0].copy()

In [333]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [334]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply in TWh<sub>el</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        # "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)

fig.show()

#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                       value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA        339.9
                            AT+50%Exp  2030 ZA        318.1
                            AT+NoExp   2030 ZA        296.4
                DKS_ZA_2050 AB+50%Exp  2050 ZA       1237.0
                            AT+100%Exp 2050 ZA       1114.6
                            AT+50%Exp  2050 ZA       1064.3
                            AT+NoExp   2050 ZA       1015.1

In [335]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand in TWh<sub>el</sub>","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                       value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA        340.0
                            AT+50%Exp  2030 ZA        318.2
                            AT+NoExp   2030 ZA        296.5
                DKS_ZA_2050 AB+50%Exp  2050 ZA       1236.9
                            AT+100%Exp 2050 ZA       1114.5
                            AT+50%Exp  2050 ZA       1064.4
                            AT+NoExp   2050 ZA       1015.1

## Energy and feedstock market balance | Hydrogen

In [336]:
df = prepare_dataframe(balance_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]!=0]
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [337]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance in TWh","year":"",
            "variable":"", 
            "scen": ""},

)

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA        33.8
                            AT+50%Exp  2030 ZA        20.7
                            AT+NoExp   2030 ZA         7.6
                DKS_ZA_2050 AB+50%Exp  2050 ZA       416.3
                            AT+100%Exp 2050 ZA       326.5
                            AT+50%Exp  2050 ZA       294.8
                            AT+NoExp   2050 ZA       263.8

In [338]:
df[["scen", "year", "variable", "value"]]

          scen  year         variable  value
0   AT+100%Exp  2030  H2 Electrolysis   26.2
3   AT+100%Exp  2030         Industry   -7.6
6   AT+100%Exp  2030     Power-to-NH3  -20.8
7   AT+100%Exp  2030  Power-to-liquid   -5.4
8   AT+100%Exp  2030              SMR    7.6
10   AT+50%Exp  2030  H2 Electrolysis   13.1
13   AT+50%Exp  2030         Industry   -7.6
16   AT+50%Exp  2030     Power-to-NH3  -10.4
17   AT+50%Exp  2030  Power-to-liquid   -2.7
18   AT+50%Exp  2030              SMR    7.6
23    AT+NoExp  2030         Industry   -7.6
28    AT+NoExp  2030              SMR    7.6
40   AB+50%Exp  2050  H2 Electrolysis  415.4
43   AB+50%Exp  2050         Industry  -27.6
44   AB+50%Exp  2050   Land transport  -19.3
45   AB+50%Exp  2050     Power-to-CH4  -59.1
46   AB+50%Exp  2050     Power-to-NH3  -55.5
47   AB+50%Exp  2050  Power-to-liquid -254.8
48   AB+50%Exp  2050              SMR    0.8
60  AT+100%Exp  2050  H2 Electrolysis  325.0
63  AT+100%Exp  2050         Industry  -51.0
64  AT+100%Exp  2050   Land transport   -1.9
65  AT+100%Exp  2050     Power-to-CH4  -36.3
66  AT+100%Exp  2050     Power-to-NH3  -72.2
67  AT+100%Exp  2050  Power-to-liquid -165.1
68  AT+100%Exp  2050              SMR    1.5
70   AT+50%Exp  2050  H2 Electrolysis  292.4
73   AT+50%Exp  2050         Industry  -51.0
74   AT+50%Exp  2050   Land transport   -1.9
75   AT+50%Exp  2050     Power-to-CH4  -40.9
76   AT+50%Exp  2050     Power-to-NH3  -54.8
77   AT+50%Exp  2050  Power-to-liquid -146.2
78   AT+50%Exp  2050              SMR    2.4
80    AT+NoExp  2050  H2 Electrolysis  260.4
83    AT+NoExp  2050         Industry  -51.0
84    AT+NoExp  2050   Land transport   -1.9
85    AT+NoExp  2050     Power-to-CH4  -45.6
86    AT+NoExp  2050     Power-to-NH3  -37.3
87    AT+NoExp  2050  Power-to-liquid -128.0
88    AT+NoExp  2050              SMR    3.3

## Energy and feedstock market balance | Liquid fuel

In [339]:
df = prepare_dataframe(balance_dict["oil"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_oil)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [340]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA       338.6
                            AT+50%Exp  2030 ZA       336.7
                            AT+NoExp   2030 ZA       334.7
                DKS_ZA_2050 AB+100%Exp 2050 ZA       235.5
                            AB+50%Exp  2050 ZA       222.2
                            AB+NoExp   2050 ZA       208.8
                            AT+100%Exp 2050 ZA       172.8
                            AT+50%Exp  2050 ZA       159.5
                            AT+NoExp   2050 ZA       146.1

## Energy and feedstock market balance | CH4

In [341]:
df = prepare_dataframe(balance_dict["gas"], idx_group, set_scen_col, rename_function=rename_gas)
df = df[df["value"]!=0]
# df.variable = df.variable.map(rename_gas)

In [342]:
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [343]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA        44.0
                            AT+50%Exp  2030 ZA        44.0
                            AT+NoExp   2030 ZA        44.0
                DKS_ZA_2050 AB+100%Exp 2050 ZA        46.1
                            AB+50%Exp  2050 ZA        48.1
                            AB+NoExp   2050 ZA        50.0
                            AT+100%Exp 2050 ZA        30.0
                            AT+50%Exp  2050 ZA        33.7
                            AT+NoExp   2050 ZA        37.4

In [344]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
1,DKS,DKS_ZA_2030,AT+100%Exp,2030,ZA,Commerce,-0.3
3,DKS,DKS_ZA_2030,AT+100%Exp,2030,ZA,Gas import,44.0
5,DKS,DKS_ZA_2030,AT+100%Exp,2030,ZA,Industry,-33.6
8,DKS,DKS_ZA_2030,AT+100%Exp,2030,ZA,SMR,-10.1
10,DKS,DKS_ZA_2030,AT+50%Exp,2030,ZA,Commerce,-0.3
12,DKS,DKS_ZA_2030,AT+50%Exp,2030,ZA,Gas import,44.0
14,DKS,DKS_ZA_2030,AT+50%Exp,2030,ZA,Industry,-33.6
17,DKS,DKS_ZA_2030,AT+50%Exp,2030,ZA,SMR,-10.1
19,DKS,DKS_ZA_2030,AT+NoExp,2030,ZA,Commerce,-0.3
21,DKS,DKS_ZA_2030,AT+NoExp,2030,ZA,Gas import,44.0
23,DKS,DKS_ZA_2030,AT+NoExp,2030,ZA,Industry,-33.6
26,DKS,DKS_ZA_2030,AT+NoExp,2030,ZA,SMR,-10.1
27,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,Biogas,1.4
28,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,Commerce,-0.3
31,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,Gas turbines,-10.7
33,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,Industry with CC,-34.5
34,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,Power-to-CH4,44.7
35,DKS,DKS_ZA_2050,AB+100%Exp,2050,ZA,SMR,-0.6
36,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,Biogas,1.4
37,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,Commerce,-0.3
40,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,Gas turbines,-12.2
42,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,Industry with CC,-34.5
43,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,Power-to-CH4,46.6
44,DKS,DKS_ZA_2050,AB+50%Exp,2050,ZA,SMR,-1.1
45,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,Biogas,1.4
46,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,Commerce,-0.3
49,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,Gas turbines,-13.6
51,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,Industry with CC,-34.5
52,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,Power-to-CH4,48.7
53,DKS,DKS_ZA_2050,AB+NoExp,2050,ZA,SMR,-1.6
54,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,Biogas,1.4
55,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,Commerce,-0.3
58,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,Gas turbines,-18.7
60,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,Industry with CC,-9.0
61,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,Power-to-CH4,28.6
62,DKS,DKS_ZA_2050,AT+100%Exp,2050,ZA,SMR,-2.0
63,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,Biogas,1.4
64,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,Commerce,-0.3
67,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,Gas turbines,-21.3
69,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,Industry with CC,-9.0
70,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,Power-to-CH4,32.3
71,DKS,DKS_ZA_2050,AT+50%Exp,2050,ZA,SMR,-3.1
72,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,Biogas,1.4
73,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,Commerce,-0.3
76,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,Gas turbines,-23.7
78,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,Industry with CC,-9.0
79,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,Power-to-CH4,35.9
80,DKS,DKS_ZA_2050,AT+NoExp,2050,ZA,SMR,-4.4

## Energy and feedstock market balance | CO2

In [345]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group, set_scen_col)
df = df[df["value"]!=0]

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [346]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA         1.0
                            AT+50%Exp  2030 ZA         0.5
                DKS_ZA_2050 AB+100%Exp 2050 ZA       117.0
                            AB+50%Exp  2050 ZA       113.6
                            AB+NoExp   2050 ZA       110.1
                            AT+100%Exp 2050 ZA        81.0
                            AT+50%Exp  2050 ZA        77.7
                            AT+NoExp   2050 ZA        74.5

## CO2 atmosphere balance

In [347]:
df = prepare_dataframe(balance_dict["co2"], idx_group, set_scen_col)

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [348]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions in Mt<sub>CO2</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA       233.8
                            AT+50%Exp  2030 ZA       233.9
                            AT+NoExp   2030 ZA       233.9
                DKS_ZA_2050 AB+100%Exp 2050 ZA        81.3
                            AB+50%Exp  2050 ZA        78.3
                            AB+NoExp   2050 ZA        75.1
                            AT+100%Exp 2050 ZA        55.7
                            AT+50%Exp  2050 ZA        52.7
                            AT+NoExp   2050 ZA        49.7

In [349]:
1e4

10000.0

# Installed Capacity

In [350]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter")
df.variable = df.variable.map(rename_to_upper_case)
df = df[~((df["variable"] == "Coal") & (df["year"] == 2050))]
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [351]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity in GW<sub>el</sub>","year":"",
            "variable":"",
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA       127.3
                            AT+50%Exp  2030 ZA       119.5
                            AT+NoExp   2030 ZA       111.9
                DKS_ZA_2050 AB+50%Exp  2050 ZA       527.1
                            AT+100%Exp 2050 ZA       483.5
                            AT+50%Exp  2050 ZA       465.7
                            AT+NoExp   2050 ZA       448.9

In [352]:
df[["scen", "year", "variable", "value"]]

          scen  year      variable  value
1   AT+100%Exp  2030          Coal   33.2
4   AT+100%Exp  2030         Hydro    3.5
5   AT+100%Exp  2030       Nuclear    2.0
6   AT+100%Exp  2030      Solar PV   34.5
9   AT+100%Exp  2030           Oil    0.4
10  AT+100%Exp  2030  Wind onshore   53.7
12   AT+50%Exp  2030          Coal   33.2
15   AT+50%Exp  2030         Hydro    3.5
16   AT+50%Exp  2030       Nuclear    2.0
17   AT+50%Exp  2030      Solar PV   32.2
20   AT+50%Exp  2030           Oil    0.4
21   AT+50%Exp  2030  Wind onshore   48.2
23    AT+NoExp  2030          Coal   33.2
26    AT+NoExp  2030         Hydro    3.5
27    AT+NoExp  2030       Nuclear    2.0
28    AT+NoExp  2030      Solar PV   30.0
31    AT+NoExp  2030           Oil    0.4
32    AT+NoExp  2030  Wind onshore   42.8
44   AB+50%Exp  2050       Battery    7.3
46   AB+50%Exp  2050  Gas turbines   11.8
48   AB+50%Exp  2050         Hydro    3.7
49   AB+50%Exp  2050       Nuclear    2.0
50   AB+50%Exp  2050      Solar PV  265.0
53   AB+50%Exp  2050           Oil    0.4
54   AB+50%Exp  2050  Wind onshore  236.9
66  AT+100%Exp  2050       Battery    7.6
68  AT+100%Exp  2050  Gas turbines   15.5
70  AT+100%Exp  2050         Hydro    3.7
71  AT+100%Exp  2050       Nuclear    2.0
72  AT+100%Exp  2050      Solar PV  240.4
75  AT+100%Exp  2050           Oil    0.4
76  AT+100%Exp  2050  Wind onshore  213.9
77   AT+50%Exp  2050       Battery    7.9
79   AT+50%Exp  2050  Gas turbines   17.2
81   AT+50%Exp  2050         Hydro    3.7
82   AT+50%Exp  2050       Nuclear    2.0
83   AT+50%Exp  2050      Solar PV  231.1
86   AT+50%Exp  2050           Oil    0.4
87   AT+50%Exp  2050  Wind onshore  203.4
88    AT+NoExp  2050       Battery    8.5
90    AT+NoExp  2050  Gas turbines   18.8
92    AT+NoExp  2050         Hydro    3.7
93    AT+NoExp  2050       Nuclear    2.0
94    AT+NoExp  2050      Solar PV  221.5
97    AT+NoExp  2050           Oil    0.4
98    AT+NoExp  2050  Wind onshore  194.0

In [353]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter")

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [354]:
fig_name = "hydrogen_installed_capacity_GW"
fig_kwargs_mod = fig_kwargs.copy()
fig_kwargs_mod["height"] = heights["2"]
fig = px.bar(
    df, 
    **fig_kwargs_mod,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity in GW<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA         3.9
                            AT+50%Exp  2030 ZA         2.4
                            AT+NoExp   2030 ZA         0.9
                DKS_ZA_2050 AB+50%Exp  2050 ZA        73.7
                            AT+100%Exp 2050 ZA        59.7
                            AT+50%Exp  2050 ZA        55.2
                            AT+NoExp   2050 ZA        50.8

In [355]:
print(df[["scen", "year", "variable", "value"]])

          scen  year         variable  value
0   AT+100%Exp  2030  H2 Electrolysis    3.0
1   AT+100%Exp  2030              SMR    0.9
3    AT+50%Exp  2030  H2 Electrolysis    1.5
4    AT+50%Exp  2030              SMR    0.9
7     AT+NoExp  2030              SMR    0.9
12   AB+50%Exp  2050  H2 Electrolysis   72.0
13   AB+50%Exp  2050              SMR    1.7
18  AT+100%Exp  2050  H2 Electrolysis   57.2
19  AT+100%Exp  2050              SMR    2.5
21   AT+50%Exp  2050  H2 Electrolysis   51.9
22   AT+50%Exp  2050              SMR    3.3
24    AT+NoExp  2050  H2 Electrolysis   46.7
25    AT+NoExp  2050              SMR    4.1

In [356]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group, set_scen_col)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [357]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs["height"] = heights["3"]
fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        #"scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:                                                      value
run_name_prefix run_name    scen       year country
DKS             DKS_ZA_2030 AT+100%Exp 2030 ZA         3.9
                            AT+50%Exp  2030 ZA         2.4
                            AT+NoExp   2030 ZA         0.9
                DKS_ZA_2050 AB+50%Exp  2050 ZA        73.7
                            AT+100%Exp 2050 ZA        59.7
                            AT+50%Exp  2050 ZA        55.2
                            AT+NoExp   2050 ZA        50.8

## Relative costs

costs / total energy consumption

## Water consumption