Plot the summary of statistics (energy balance, optimal capacity, ...) 

**Prerequisites**

* Execute "make_stats_dict.py" before using this notebook. The script make_stats_dict creates csv for the metrics for all runs of multiple config files. 
* Install the environment envs/pypsa-earth-vis.yaml

In [1]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px

from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    add_totals_to_plot,
    add_balance_totals_to_plot,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

In [2]:
run_name_prefix = "DKS" # Experiment name
run_name_prefix = "MAPaper" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary_v1"
sdir.mkdir(exist_ok=True, parents=True)

In [3]:
COUNTRY = ['MA'] #, 'EG', 'MA', 'ZA', 'CL'


# select and define index group (multiindex) for plots: which solutions to show at once

# idx_group = idx_slice[["DKS"],:,COUNTRY,[2030, 2050],["1H"]]
idx_group = idx_slice[["MAPaper"],:,COUNTRY,[2035]]
idx_group_name = "".join(COUNTRY) + "_MAIN"

print(idx_group_name) 
print(idx_group)

scen_filter = ['Exp-H2v1.0', 'Exp-H2v1.0-Co2L1.09','IR-HBIv1.0+STEELv1.0','IR-HBIv1.0+STEELv1.0-Co2L1.09']

# 'Exp', 'Exp-Co2L1.09', 'Exp-H2v1.0', 'Exp-H2v1.0-Co2L1.09',
#        'Exp-HBIv1.0+STEELv1.0', 'Exp-HBIv1.0+STEELv1.0-Co2L1.09', 'IR',
#        'IR-Co2L1.09', 'IR-H2v1.0-Co2L1.09', 'IR-HBIv1.0+STEELv1.0',
#        'IR-HBIv1.0+STEELv1.0-Co2L1.09'

scen_order = scen_filter if scen_filter else [] #[] # option to specify order of scenarios in the plot


# def set_scen_col(df):
#     """
#     Set combined scenario str (for plots).
#     NB: This is specific to the experiment and should be adapted for other experiments.
#     """
#     df = df.copy()

#     df["scen"] = df["eopts"] + "+" + df["sopts"]
#     df = df.drop(columns=["eopts", "sopts"])
#     #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
#     #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

#     return df

def set_scen_col_MAPaper(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    demand_info = df["demand"]#.map({"Exp": ""})

    # Add export info based on 'eopts', handling NaN and string values
    export_info = (
        df["eopts"].apply(lambda x: 
            x if isinstance(x, str) and "v" in x
            else ("" if pd.isna(x) or str(x) == "" else "")
        )
        .replace("", "", regex=False)
        .apply(lambda x: f"-{x}" if x else "")
    )


    sopts_info = df["sopts"].replace("1H", "", regex=False).apply(lambda x: f"-{x}" if x else "")

    opts_info = (
        df["opts"].apply(
            lambda x: x if isinstance(x, str) and "Co2L" in x
            else ("" if pd.isna(x) or str(x) == "" else "")
        )
        .replace("", "", regex=False)
        .apply(lambda x: f"-{x}" if x else "")
    )
    # Combine
    df["scen"] = demand_info + export_info + sopts_info + opts_info

    df = df.drop(columns=["eopts", "sopts", "demand", "opts"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

def set_scen_col_DKS(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    # Set base scen value based on 'demand'
    scen = df["demand"].map({"RF": "AB", "EL": "AT"})
    # Add export info
    export_info = ""
    # Add export info based on 'eopts', handling NaN and string values
    export_info = df["eopts"].apply(
        lambda x: "50EX" if isinstance(x, str) and "v0.5" in x
        else ("" if pd.isna(x) or str(x) == "" else "100EX")
    )
    # Combine
    df["scen"] = scen + export_info.replace("", "", regex=False).apply(lambda x: f"-{x}" if x else "") + df["sopts"].replace("1H", "", regex=False)
    df = df.drop(columns=["eopts", "sopts", "demand"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

set_scen_col = set_scen_col_MAPaper

MA_MAIN
(['MAPaper'], slice(None, None, None), ['MA'], [2035])

## Navigation

### Main Sections
[⬇️ Go to Plotting](#plotting)
- [⬇️ Energy market balance | Electricity](#energy-market-balance--electricity)
- [⬇️ Energy and feedstock market balance | Hydrogen](#energy-and-feedstock-market-balance--hydrogen)
- [⬇️ Energy and feedstock market balance | Liquid fuel](#energy-and-feedstock-market-balance--liquid-fuel)
- [⬇️ Energy and feedstock market balance | CH4](#energy-and-feedstock-market-balance--ch4)
- [⬇️ Energy and feedstock market balance | CO2](#energy-and-feedstock-market-balance--co2)
- [⬇️ CO2 atmosphere balance](#co2-atmosphere-balance)

[⬇️ Go to Installed Capacity](#installed-capacity)

[⬇️ Go to Relative costs](#relative-costs)

[⬇️ Go to Water consumption](#water-consumption)

In [4]:
def add_production_consumption_legend_groups(fig, df):
    """
    Add legend groups for Production (positive values) and Consumption (negative values).
    
    Parameters:
    -----------
    fig : plotly.graph_objects.Figure
        The plotly figure to modify
    df : pandas.DataFrame
        The dataframe containing the data with 'variable' and 'value' columns
    
    Returns:
    --------
    fig : plotly.graph_objects.Figure
        The modified figure with legend groups
    """
    # Add legend groups for Production (positive values) and Consumption (negative values)
    for trace in fig.data:
        # Get the variable name from the trace
        variable_name = trace.name
        
        # Check if this variable typically has positive or negative values in the data
        variable_data = df[df['variable'] == variable_name]['value']
        
        if len(variable_data) > 0:
            # Determine if this variable is primarily production (positive) or consumption (negative)
            avg_value = variable_data.mean()
            
            if avg_value > 0:
                trace.legendgroup = "Production"
                trace.legendgrouptitle = {"text": "Production"}
            else:
                trace.legendgroup = "Consumption" 
                trace.legendgrouptitle = {"text": "Consumption"}
    
    return fig

In [5]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "discountrate"] #, , "opts", "demand" "sopts"


for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_H2.csv
Imported oil from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_oil.csv
Imported gas from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_gas.csv
Imported co2 stored from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_co2 stored.csv
Imported co2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/balance_dict_co2.csv
Imported AC from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/optimal_capacity_dict_AC.csv
Imported H2 from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/optimal_capacity_dict_H2.csv
Imported capex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/costs_dict_capex.csv
Imported opex from /mnt/data/gsa/pypsa-earth-custom-lukas/results/MAPaper_summary_v1/costs_dict_opex.csv

# Plotting

In [6]:
width = 800
heights = {"1": 350,"2": 500,"3": 600,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    # facet_row="run_name",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

## Energy market balance | Electricity

In [7]:
# Check what country-demand combinations are available
stats_df = balance_dict["AC"]
country_demand_combos = stats_df.reset_index()[['country', 'demand']].drop_duplicates()
print("Available country-demand combinations:")
print(country_demand_combos.sort_values(['country', 'demand']))

Available country-demand combinations:
  country demand
0      MA    Exp
3      MA     IR

In [8]:
stats_df.reset_index()

,run_name_prefix,run_name,country,year,opts,sopts,demand,eopts,AC,BEV charger,...,services urban decentral air heat pump,services urban decentral resistive heater,solar,urban central air heat pump,urban central gas CHP,urban central gas CHP CC,urban central resistive heater,urban central solid biomass CHP,urban central solid biomass CHP CC,EAF
0,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,Exp,NaN,-35.0,-6.7,...,-0.0,-0.0,21.3,-0.0,0.8,0.0,-0.3,0.0,0.0,NaN
1,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,Exp,H2v1.0,-35.0,-6.7,...,-0.0,-0.0,27.6,-0.0,0.6,0.0,-0.2,0.0,0.0,NaN
2,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,Exp,HBIv1.0+STEELv1.0,-35.0,-6.7,...,-0.0,-0.0,22.7,-0.0,0.7,0.0,-0.3,0.0,0.0,-0.6
3,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,IR,NaN,-35.0,-6.7,...,-0.0,-0.0,21.4,-0.0,0.8,0.0,-0.3,0.0,0.0,NaN
4,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,IR,H2v1.0,-35.0,-6.7,...,-0.0,-0.0,27.6,-0.0,0.6,0.0,-0.2,0.0,0.0,NaN
5,MAPaper,MAPaper_2035,MA,2035,Co2L1.09,1H,IR,HBIv1.0+STEELv1.0,-35.0,-6.7,...,-0.0,-0.0,22.7,-0.0,0.7,0.0,-0.3,0.0,0.0,-0.6
6,MAPaper,MAPaper_2035,MA,2035,NaN,1H,Exp,NaN,-35.0,-6.7,...,-0.0,-0.0,15.2,-0.0,0.8,0.0,-0.0,0.0,0.0,NaN
7,MAPaper,MAPaper_2035,MA,2035,NaN,1H,Exp,H2v1.0,-35.0,-6.7,...,-0.0,-0.0,20.8,-0.0,0.6,0.0,-0.0,0.0,0.0,NaN
8,MAPaper,MAPaper_2035,MA,2035,NaN,1H,Exp,HBIv1.0+STEELv1.0,-35.0,-6.7,...,-0.0,-0.0,16.6,-0.0,0.8,0.0,-0.0,0.0,0.0,-0.6
9,MAPaper,MAPaper_2035,MA,2035,NaN,1H,IR,NaN,-35.0,-6.7,...,-0.0,-0.0,15.2,-0.0,0.8,0.0,-0.0,0.0,0.0,NaN
10,MAPaper,MAPaper_2035,MA,2035,NaN,1H,IR,H2v1.0,-35.0,-6.7,...,-0.0,-0.0,20.8,-0.0,0.6,0.0,-0.0,0.0,0.0,NaN
11,MAPaper,MAPaper_2035,MA,2035,NaN,1H,IR,HBIv1.0+STEELv1.0,-35.0,-6.7,...,-0.0,-0.0,16.6,-0.0,0.8,0.0,-0.0,0.0,0.0,-0.6

In [9]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.scen.unique()

array(['Exp', 'Exp-Co2L1.09', 'Exp-H2v1.0', 'Exp-H2v1.0-Co2L1.09',
       'Exp-HBIv1.0+STEELv1.0', 'Exp-HBIv1.0+STEELv1.0-Co2L1.09', 'IR',
       'IR-Co2L1.09', 'IR-H2v1.0', 'IR-H2v1.0-Co2L1.09',
       'IR-HBIv1.0+STEELv1.0', 'IR-HBIv1.0+STEELv1.0-Co2L1.09'],
      dtype=object)

In [10]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df.variable = df.variable.map(rename_to_upper_case)
df = df.query("scen in @scen_filter") if scen_filter else df if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [11]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply [TWh<sub>el</sub>]",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, 
    facet_row_spacing=0.1,
)

# Update layout for bar traces only (before adding scatter traces)
fig.update_traces(textposition='inside', textangle=0, selector=dict(type='bar'))
fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))

# Add totals using the reusable function
fig = add_totals_to_plot(fig, supply_sum_df)

fig.update_layout(legend_traceorder="reversed",)

print("Totals per scenario and year:", supply_sum_df)



fig.show()

save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0  115.9
1  117.6
2   96.4
3   99.3

In [12]:
# Debug: Check the totals data structure
print("supply_sum_df structure:")
print(supply_sum_df)
print("\nUnique years in totals:", supply_sum_df.reset_index()['year'].unique())
print("Unique scenarios in totals:", supply_sum_df.reset_index()['scen'].unique())

supply_sum_df structure:
  run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0  115.9
1  117.6
2   96.4
3   99.3

Unique years in totals: [2035]
Unique scenarios in totals: ['Exp-H2v1.0' 'Exp-H2v1.0-Co2L1.09' 'IR-HBIv1.0+STEELv1.0'
 'IR-HBIv1.0+STEELv1.0-Co2L1.09']

In [13]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand [TWh<sub>el</sub>]","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

# Add totals using the reusable function
fig = add_totals_to_plot(fig, demand_sum_df)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0  115.8
1  117.4
2   96.4
3   99.2

## Energy and feedstock market balance | Hydrogen

In [14]:
df = prepare_dataframe(balance_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df.query("scen in @scen_filter") if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [15]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance [TWh<sub>H2</sub>]","year":"",
            "variable":"", 
            "scen": ""},

)

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

# Add supply and demand totals for balance plot
fig = add_balance_totals_to_plot(fig, supply_sum_df, demand_sum_df, 
                                y_offset=5,
                                supply_label='',
                                demand_label='')

print("Supply totals per scenario and year:", supply_sum_df)
print("Demand totals per scenario and year:", demand_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_{fig_name}")

Supply totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0   20.5
1   20.5
2    6.5
3    6.5
Demand totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0   20.5
1   20.5
2    6.6
3    6.6

In [16]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
29,MAPaper,MAPaper_2035,Exp-H2v1.0,2035,MA,H2 Electrolysis,20.5
30,MAPaper,MAPaper_2035,Exp-H2v1.0,2035,MA,H2 export,-17.0
33,MAPaper,MAPaper_2035,Exp-H2v1.0,2035,MA,Industry,-2.1
34,MAPaper,MAPaper_2035,Exp-H2v1.0,2035,MA,Land transport,-1.2
38,MAPaper,MAPaper_2035,Exp-H2v1.0,2035,MA,Power-to-NH3,-0.2
43,MAPaper,MAPaper_2035,Exp-H2v1.0-Co2L1.09,2035,MA,H2 Electrolysis,20.5
44,MAPaper,MAPaper_2035,Exp-H2v1.0-Co2L1.09,2035,MA,H2 export,-17.0
47,MAPaper,MAPaper_2035,Exp-H2v1.0-Co2L1.09,2035,MA,Industry,-2.1
48,MAPaper,MAPaper_2035,Exp-H2v1.0-Co2L1.09,2035,MA,Land transport,-1.2
52,MAPaper,MAPaper_2035,Exp-H2v1.0-Co2L1.09,2035,MA,Power-to-NH3,-0.2
140,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0,2035,MA,DRI,-3.0
141,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0,2035,MA,H2 Electrolysis,6.5
145,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0,2035,MA,Industry,-2.2
146,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0,2035,MA,Land transport,-1.2
150,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0,2035,MA,Power-to-NH3,-0.2
154,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0-Co2L1.09,2035,MA,DRI,-3.0
155,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0-Co2L1.09,2035,MA,H2 Electrolysis,6.5
159,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0-Co2L1.09,2035,MA,Industry,-2.2
160,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0-Co2L1.09,2035,MA,Land transport,-1.2
164,MAPaper,MAPaper_2035,IR-HBIv1.0+STEELv1.0-Co2L1.09,2035,MA,Power-to-NH3,-0.2

## Energy and feedstock market balance | Liquid fuel

In [33]:
df = prepare_dataframe(balance_dict["oil"], idx_group, set_scen_col, rename_function=rename_oil)
df = df[df["value"]!=0]
df = df.query("scen in @scen_filter") if scen_filter else df if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [35]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        # "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance [TWh]","year":"",
            "variable":"", 
            "scen":""},

)

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

# Add supply and demand totals for balance plot
fig = add_balance_totals_to_plot(fig, supply_sum_df, demand_sum_df, 
                                y_offset=5,
                                supply_label='',
                                demand_label='')

print("Totals per scenario and year:", demand_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0  124.6
1  124.6
2  124.8
3  124.8

## Energy and feedstock market balance | CH4

In [38]:
df = prepare_dataframe(balance_dict["gas"], idx_group, set_scen_col, rename_function=rename_gas)

df = df.query("scen in @scen_filter") if scen_filter else df if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [39]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance [TWh]","year":"",
            "variable":"", 
            "scen":""},

)
# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

# Add supply and demand totals for balance plot
fig = add_balance_totals_to_plot(fig, supply_sum_df, demand_sum_df, 
                                y_offset=5,
                                supply_label='',
                                demand_label='')

print("Totals per scenario and year:", demand_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0   53.5
1   37.0
2   51.9
3   42.1

## Energy and feedstock market balance | CO2

In [45]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group, set_scen_col, rename_function=rename_co2)
df = df[df["value"]!=0]

df = df.query("scen in @scen_filter") if scen_filter else df if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [46]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
# # Add legend groups for Production and Consumption
# fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)


print("Totals per scenario and year:", demand_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year: Empty DataFrame
Columns: [run_name_prefix, run_name, scen, year, country, value]
Index: []

## CO2 atmosphere balance

In [47]:
df = prepare_dataframe(balance_dict["co2"], idx_group, set_scen_col, rename_function=rename_co2)

df = df.query("scen in @scen_filter") if scen_filter else df if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [48]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions [Mt<sub>CO2</sub>]",
            "year":"",
            "variable":" ", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0  111.7
1   78.5
2  112.6
3   78.4

In [25]:
1e4

10000.0

# Installed Capacity

In [49]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group, set_scen_col, rename_function=rename_electricity)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter") if scen_filter else df
df.variable = df.variable.map(rename_to_upper_case)
df = df[~((df["variable"] == "Coal") & (df["year"] == 2050))]
(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [50]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity [GW<sub>el</sub>]","year":"",
            "variable":"",
            "scen":""},
)
update_layout(fig)

# Add totals for installed capacity
fig = add_totals_to_plot(fig, supply_sum_df, textfont_size=14)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0   35.8
1   48.6
2   29.3
3   43.0

In [55]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group, set_scen_col, rename_function=rename_h2)
df = df[df["value"]<4000] #drop loadshedding capacity
df = df.query("scen in @scen_filter") if scen_filter else df

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [56]:
fig_name = "hydrogen_installed_capacity_GW"
fig_kwargs_mod = fig_kwargs.copy()
fig_kwargs_mod["height"] = 400 #heights["1"]
fig = px.bar(
    df, 
    **fig_kwargs_mod,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity [GW]<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

# Add totals for hydrogen installed capacity
fig = add_totals_to_plot(fig, supply_sum_df, textfont_size=14, y_offset=0)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
save_plotly_fig(df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0    2.9
1    4.0
2    0.8
3    0.9

In [57]:
print(df[["scen", "year", "variable", "value"]])

                             scen  year                  variable  value
6                      Exp-H2v1.0  2035           H2 Electrolysis    2.8
7                      Exp-H2v1.0  2035  Methanol steam reforming    0.1
9             Exp-H2v1.0-Co2L1.09  2035           H2 Electrolysis    4.0
30           IR-HBIv1.0+STEELv1.0  2035           H2 Electrolysis    0.8
33  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035           H2 Electrolysis    0.9

In [ ]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group, set_scen_col)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# Add legend groups for Production and Consumption
fig = add_production_consumption_legend_groups(fig, df)

update_layout(fig)

# Add supply and demand totals for balance plot
fig = add_balance_totals_to_plot(fig, supply_sum_df, demand_sum_df, 
                                y_offset=5,
                                supply_label='',
                                demand_label='')

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [32]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs_mod = fig_kwargs.copy()
fig_kwargs_mod["height"] = heights["3"]
# fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs_mod,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        "scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:   run_name_prefix      run_name                           scen  year country  \
0         MAPaper  MAPaper_2035                     Exp-H2v1.0  2035      MA
1         MAPaper  MAPaper_2035            Exp-H2v1.0-Co2L1.09  2035      MA
2         MAPaper  MAPaper_2035           IR-HBIv1.0+STEELv1.0  2035      MA
3         MAPaper  MAPaper_2035  IR-HBIv1.0+STEELv1.0-Co2L1.09  2035      MA

   value
0    2.9
1    4.0
2    0.8
3    0.9

## Relative costs

costs / total energy consumption

## Water consumption