Plot the summary of statistics (energy balance, optimal capacity, ...) 

**Prerequisites**

* Execute "make_stats_dict.py" before using this notebook. The script make_stats_dict creates csv for the metrics for all runs of multiple config files. 
* Install the environment envs/pypsa-earth-vis.yaml

In [4]:
%load_ext autoreload
%autoreload 2
from pathlib import Path
import pandas as pd
idx_slice = pd.IndexSlice
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning) # Comment out for debugging and development
warnings.simplefilter(action='ignore', category=DeprecationWarning) # Comment out for debugging and development
import plotly.express as px

from plot_helpers import (
    chdir_to_parent_dir,
    read_stats_dict,
    drop_index_levels, 
    update_layout, 
    prepare_dataframe,
    get_supply_demand_from_balance,
    rename_electricity, 
    rename_h2,
    rename_gas,
    rename_oil,
    rename_co2,
    rename_costs,
    rename_to_upper_case,
    colors,
    nice_title,
    save_plotly_fig)

chdir_to_parent_dir()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
run_name_prefix = "DKS" # Experiment name

sdir = Path.cwd() / "results"/ f"{run_name_prefix}_summary"
sdir.mkdir(exist_ok=True, parents=True)

In [6]:
balance_dict = read_stats_dict("balance_dict", sdir, keys=["AC", "H2", "oil", "gas", "co2 stored", "co2"])
optimal_capacity_dict = read_stats_dict("optimal_capacity_dict", sdir, keys=["AC", "H2"])
costs_dict = read_stats_dict("costs_dict", sdir, keys=["capex", "opex"])

# simplify index for plotting: define a scen_str column and drop all other columns
#NB: the following is specific to the experiment

index_levels_to_drop=["simpl", "clusters", "ll", "opts", "discountrate", "demand"] #, "sopts"


for key in balance_dict.keys():
    balance_dict[key] = drop_index_levels(balance_dict[key], to_drop=index_levels_to_drop)

for key in optimal_capacity_dict.keys():
    optimal_capacity_dict[key] = drop_index_levels(optimal_capacity_dict[key], to_drop=index_levels_to_drop)
    
for key in costs_dict.keys():
    costs_dict[key] = drop_index_levels(costs_dict[key], to_drop=index_levels_to_drop)

Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_H2.csv
Imported oil from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_oil.csv
Imported gas from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_gas.csv
Imported co2 stored from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_co2 stored.csv
Imported co2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\balance_dict_co2.csv
Imported AC from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\optimal_capacity_dict_AC.csv
Imported H2 from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\optimal_capacity_dict_H2.csv
Imported capex from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\costs_dict_capex.csv
Imported opex from C:\Users\ljansen\projects\pypsa-earth-custom\results\DKS_summary\costs_dict_opex.csv

In [7]:
def set_scen_col(df):
    """
    Set combined scenario str (for plots).
    NB: This is specific to the experiment and should be adapted for other experiments.
    """
    df = df.copy()
    
    df["scen"] = df["eopts"] + "+" + df["sopts"]
    df = df.drop(columns=["eopts", "sopts"])
    #df["scen"] = df.apply(lambda row: "_".join([f"{col}_{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)
    #df["scen"] = df.apply(lambda row: "_".join([f"{row[col]}" for col in df.columns if col not in cols_to_ignore]), axis=1)

    return df

# Plotting

In [8]:
print(balance_dict["AC"].index.names)
print(balance_dict["AC"].index)

['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'eopts']
MultiIndex([('DKS', 'DKS_EG_2050_eopts', 'EG', 2050, '3H', ...),
            ('DKS', 'DKS_EG_2050_eopts', 'EG', 2050, '3H', ...),
            ('DKS', 'DKS_EG_2050_eopts', 'EG', 2050, '3H', ...),
            ('DKS', 'DKS_EG_2050_eopts', 'EG', 2050, '3H', ...),
            ('DKS', 'DKS_EG_2050_eopts', 'EG', 2050, '3H', ...)],
           names=['run_name_prefix', 'run_name', 'country', 'year', 'sopts', 'eopts'])

In [9]:
width = 700
heights = {"1": 300,"2": 600,"3": 700,}

fig_kwargs = dict(
    x="scen", 
    y="value", 
    color="variable", 
    facet_col="year", 
    facet_row="run_name",
    barmode="relative", 
    text="value", 
    #facet_col_wrap=1, facet_col_spacing=0.07,
    width=width, 
    height=heights["2"],
    text_auto =".0f",
)

scen_order = [] # option to specify order of scenarios in the plot

In [10]:
# balance_dict["gas"].query("year == 2050 and country == 'ZA'").T

In [11]:
# balance_dict["co2 stored"].query("year == 2050 and country == 'ZA'").T

In [12]:
# select and define index group (multiindex) for plots: which solutions to show at once

idx_group = idx_slice[["DKS"],:,["EG"],[2050],["3H"]]
idx_group_name = ""

print(idx_group_name) 
print(idx_group)

(['DKS'], slice(None, None, None), ['EG'], [2050], ['3H'])

## Energy market balance | Electricity

In [13]:
balance_dict["AC"]

                                                                                  AC  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0            -310.7
                                                     H2m1.0+H2v0.5            -310.7
                                                     H2m1.0+NH3v1.0           -310.7
                                                     H2m1.0+NH3v1.0+FTv1.0    -310.7
                                                     H2v1.01+NH3v1.01+FTv1.01 -310.7

                                                                               BEV charger  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                   -16.8
                                                     H2m1.0+H2v0.5                   -16.8
                                                     H2m1.0+NH3v1.0                  -16.8
                                                     H2m1.0+NH3v1.0+FTv1.0           -16.8
                                                     H2v1.01+NH3v1.01+FTv1.01        -16.8

                                                                               CCGT  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0              2.7
                                                     H2m1.0+H2v0.5              2.7
                                                     H2m1.0+NH3v1.0             2.7
                                                     H2m1.0+NH3v1.0+FTv1.0      2.8
                                                     H2v1.01+NH3v1.01+FTv1.01   0.7

                                                                                 DAC  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0              -2.7
                                                     H2m1.0+H2v0.5              -2.7
                                                     H2m1.0+NH3v1.0             -2.7
                                                     H2m1.0+NH3v1.0+FTv1.0      -3.6
                                                     H2v1.01+NH3v1.01+FTv1.01 -941.7

                                                                               Fischer-Tropsch  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                        -1.2
                                                     H2m1.0+H2v0.5                        -1.2
                                                     H2m1.0+NH3v1.0                       -1.2
                                                     H2m1.0+NH3v1.0+FTv1.0                -1.3
                                                     H2v1.01+NH3v1.01+FTv1.01            -63.7

                                                                               H2 Electrolysis  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                      -935.4
                                                     H2m1.0+H2v0.5                      -847.5
                                                     H2m1.0+NH3v1.0                     -952.6
                                                     H2m1.0+NH3v1.0+FTv1.0              -971.1
                                                     H2v1.01+NH3v1.01+FTv1.01         -17152.3

                                                                               H2 Fuel Cell  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                      0.0
                                                     H2m1.0+H2v0.5                      0.0
                                                     H2m1.0+NH3v1.0                     0.0
                                                     H2m1.0+NH3v1.0+FTv1.0              0.0
                                                     H2v1.01+NH3v1.01+FTv1.01           0.0

                                                                               Haber-Bosch  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                    -0.0
                                                     H2m1.0+H2v0.5                    -0.0
                                                     H2m1.0+NH3v1.0                   -1.3
                                                     H2m1.0+NH3v1.0+FTv1.0            -1.3
                                                     H2v1.01+NH3v1.01+FTv1.01         -0.0

                                                                               OCGT  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0              0.0
                                                     H2m1.0+H2v0.5              0.0
                                                     H2m1.0+NH3v1.0             0.0
                                                     H2m1.0+NH3v1.0+FTv1.0      0.0
                                                     H2v1.01+NH3v1.01+FTv1.01   0.0

                                                                               PHS  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0            -0.0
                                                     H2m1.0+H2v0.5            -0.0
                                                     H2m1.0+NH3v1.0           -0.0
                                                     H2m1.0+NH3v1.0+FTv1.0    -0.0
                                                     H2v1.01+NH3v1.01+FTv1.01 -0.0

                                                                               ...  \
run_name_prefix run_name          country year sopts eopts                     ...
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0             ...
                                                     H2m1.0+H2v0.5             ...
                                                     H2m1.0+NH3v1.0            ...
                                                     H2m1.0+NH3v1.0+FTv1.0     ...
                                                     H2v1.01+NH3v1.01+FTv1.01  ...

                                                                               services rural resistive heater  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                        -0.0
                                                     H2m1.0+H2v0.5                                        -0.0
                                                     H2m1.0+NH3v1.0                                       -0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                                -0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                             -0.0

                                                                               services urban decentral air heat pump  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                               -0.0
                                                     H2m1.0+H2v0.5                                               -0.0
                                                     H2m1.0+NH3v1.0                                              -0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                                       -0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                                    -0.0

                                                                               services urban decentral resistive heater  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                                  -0.0
                                                     H2m1.0+H2v0.5                                                  -0.0
                                                     H2m1.0+NH3v1.0                                                 -0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                                          -0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                                       -0.0

                                                                                 solar  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0               755.5
                                                     H2m1.0+H2v0.5               691.7
                                                     H2m1.0+NH3v1.0              763.4
                                                     H2m1.0+NH3v1.0+FTv1.0       775.0
                                                     H2v1.01+NH3v1.01+FTv1.01  12751.5

                                                                               urban central air heat pump  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                    -0.0
                                                     H2m1.0+H2v0.5                                    -0.0
                                                     H2m1.0+NH3v1.0                                   -0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                            -0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                        -10.2

                                                                               urban central gas CHP  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                               0.0
                                                     H2m1.0+H2v0.5                               0.0
                                                     H2m1.0+NH3v1.0                              0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                       0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                    0.0

                                                                               urban central gas CHP CC  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                  0.0
                                                     H2m1.0+H2v0.5                                  0.0
                                                     H2m1.0+NH3v1.0                                 0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                          0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                       0.0

                                                                               urban central resistive heater  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                       -0.4
                                                     H2m1.0+H2v0.5                                       -0.4
                                                     H2m1.0+NH3v1.0                                      -0.4
                                                     H2m1.0+NH3v1.0+FTv1.0                               -0.4
                                                     H2v1.01+NH3v1.01+FTv1.01                           -32.9

                                                                               urban central solid biomass CHP  \
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                         0.0
                                                     H2m1.0+H2v0.5                                         0.0
                                                     H2m1.0+NH3v1.0                                        0.0
                                                     H2m1.0+NH3v1.0+FTv1.0                                 0.0
                                                     H2v1.01+NH3v1.01+FTv1.01                              0.0

                                                                               urban central solid biomass CHP CC
run_name_prefix run_name          country year sopts eopts
DKS             DKS_EG_2050_eopts EG      2050 3H    H2m1.0+H2v1.0                                            6.9
                                                     H2m1.0+H2v0.5                                            7.0
                                                     H2m1.0+NH3v1.0                                           6.9
                                                     H2m1.0+NH3v1.0+FTv1.0                                    7.3
                                                     H2v1.01+NH3v1.01+FTv1.01                                16.1

[5 rows x 38 columns]

In [14]:
df = prepare_dataframe(balance_dict["AC"], idx_group, set_scen_col)
df.variable = df.variable.map(rename_electricity).map(rename_to_upper_case)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [15]:
supply_df

,run_name_prefix,run_name,scen,year,country,variable,value
0,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Battery,63.2
1,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,CHP,7.0
2,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Gas turbines,2.7
3,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Hydro,7.7
4,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Nuclear,34.4
5,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Solar PV,691.7
6,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Wind onshore,691.4
7,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Battery,63.8
8,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,CHP,6.9
9,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Gas turbines,2.7
10,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Hydro,7.7
11,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Nuclear,34.6
12,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Solar PV,755.5
13,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Wind onshore,715.4
14,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Battery,63.3
15,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,CHP,6.9
16,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Gas turbines,2.7
17,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Hydro,7.7
18,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Nuclear,34.6
19,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Solar PV,763.4
20,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Wind onshore,725.8
21,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Battery,62.4
22,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,CHP,7.3
23,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Gas turbines,2.8
24,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Hydro,7.7
25,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Nuclear,34.6
26,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Solar PV,775.0
27,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Wind onshore,733.3
28,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Battery,885.7
29,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,CHP,16.1
30,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Gas turbines,0.7
31,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Hydro,7.7
32,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Nuclear,38.6
33,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Solar PV,12751.5
34,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Wind onshore,6002.3

In [16]:
fig_name = "electricity_supply_TWh"
fig = px.bar(
    supply_df, 
    **fig_kwargs,
    labels={"value":"Electricity supply in TWh<sub>el</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)

fig.show()

#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG        1498.1
                                  H2m1.0+H2v1.0+3H            2050 EG        1586.6
                                  H2m1.0+NH3v1.0+3H           2050 EG        1604.4
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG        1623.1
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       19702.6

In [17]:
fig_name = "electricity_demand_TWh"
fig = px.bar(
    demand_df, 
    **fig_kwargs,
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    labels={"value":"Electricity demand in TWh<sub>el</sub>","year":"",
            "variable":"", 
            "scen":""},
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(demand_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG        1498.2
                                  H2m1.0+H2v1.0+3H            2050 EG        1586.6
                                  H2m1.0+NH3v1.0+3H           2050 EG        1604.6
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG        1623.2
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       19702.6

## Energy and feedstock market balance | Hydrogen

In [18]:
df = prepare_dataframe(balance_dict["H2"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_h2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [19]:
df

,run_name_prefix,run_name,scen,year,country,variable,value
0,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Power-to-liquid,-228.0
1,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,H2 Electrolysis,601.8
3,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,H2 export,-62.5
4,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Shipping,-2.9
6,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Power-to-gas,-303.0
7,DKS,DKS_EG_2050_eopts,H2m1.0+H2v0.5+3H,2050,EG,Land transport,-5.3
9,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Power-to-liquid,-228.0
10,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,H2 Electrolysis,664.1
12,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,H2 export,-125.0
13,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Shipping,-2.9
15,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Power-to-gas,-302.9
16,DKS,DKS_EG_2050_eopts,H2m1.0+H2v1.0+3H,2050,EG,Land transport,-5.3
18,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Power-to-liquid,-228.0
19,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,H2 Electrolysis,676.3
21,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,H2 export,-125.0
22,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Shipping,-2.9
23,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Ammonia synthesis,-12.1
24,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Power-to-gas,-303.0
25,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+3H,2050,EG,Land transport,-5.3
27,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Power-to-liquid,-241.1
28,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,H2 Electrolysis,689.5
30,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,H2 export,-125.0
31,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Shipping,-2.9
32,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Ammonia synthesis,-12.1
33,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Power-to-gas,-303.1
34,DKS,DKS_EG_2050_eopts,H2m1.0+NH3v1.0+FTv1.0+3H,2050,EG,Land transport,-5.3
36,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Power-to-liquid,-12081.6
37,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,H2 Electrolysis,12178.1
39,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,H2 export,-18.0
40,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Shipping,-2.9
42,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Power-to-gas,-70.3
43,DKS,DKS_EG_2050_eopts,H2v1.01+NH3v1.01+FTv1.01+3H,2050,EG,Land transport,-5.3

In [20]:
supply_sum_df

                                                                              value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG         601.8
                                  H2m1.0+H2v1.0+3H            2050 EG         664.1
                                  H2m1.0+NH3v1.0+3H           2050 EG         676.3
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG         689.5
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       12178.1

In [21]:
demand_sum_df

                                                                              value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG         601.7
                                  H2m1.0+H2v1.0+3H            2050 EG         664.1
                                  H2m1.0+NH3v1.0+3H           2050 EG         676.3
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG         689.5
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       12178.1

In [22]:
fig_name = "hydrogen_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["hydrogen"],
    category_orders={
        "variable":list(colors["hydrogen"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"H2 balance in TWh","year":"",
            "variable":"", 
            "scen": ""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG         601.7
                                  H2m1.0+H2v1.0+3H            2050 EG         664.1
                                  H2m1.0+NH3v1.0+3H           2050 EG         676.3
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG         689.5
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       12178.1

## Energy and feedstock market balance | Liquid fuel

In [23]:
df = prepare_dataframe(balance_dict["oil"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_oil)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [24]:
fig_name = "liquid_fuel_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["oil"],
    category_orders={
        "variable":list(colors["oil"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"Liquid fuel balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                              value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG        174.1
                                  H2m1.0+H2v1.0+3H            2050 EG        174.1
                                  H2m1.0+NH3v1.0+3H           2050 EG        174.1
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG        184.1
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       9218.4

## Energy and feedstock market balance | CH4

In [25]:
df = prepare_dataframe(balance_dict["gas"], idx_group, set_scen_col)
df = df[df["value"]!=0]
df.variable = df.variable.map(rename_gas)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [26]:
fig_name = "CH4_balance_TWh"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["gas"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CH4 balance in TWh","year":"",
            "variable":"", 
            "scen":""},

)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                             value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG       240.6
                                  H2m1.0+H2v1.0+3H            2050 EG       240.5
                                  H2m1.0+NH3v1.0+3H           2050 EG       240.6
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG       240.6
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       232.8

## Energy and feedstock market balance | CO2

In [27]:
df = prepare_dataframe(balance_dict["co2 stored"], idx_group, set_scen_col)
df = df[df["value"]!=0]

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [28]:
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["gas"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    labels={"value":"CO<sub>2</sub> Capture (+) and Usage (-) in Mt","year":"","variable":"", "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", demand_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_CO2_capture_and_usage_Mt")

Totals per scenario and year:                                                                              value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG        157.2
                                  H2m1.0+H2v1.0+3H            2050 EG        157.2
                                  H2m1.0+NH3v1.0+3H           2050 EG        157.2
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG        159.9
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       2481.4

## CO2 atmosphere balance

In [29]:
df = prepare_dataframe(balance_dict["co2"], idx_group, set_scen_col)

df.variable = df.variable.map(rename_co2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [30]:
fig_name = "co2_emissions_mt"
fig = px.bar(
    df, 
    **fig_kwargs,
    labels={"value":"CO2 emissions in Mt<sub>CO2</sub>",
            "year":"",
            "variable":"", 
            "scen":""
            },
    color_discrete_map=colors["co2"],
    category_orders={
        "variable":list(colors["co2"].keys()),
        "scen": scen_order
        },
    #facet_col_wrap=1, facet_col_spacing=0.07,
)
fig.update_layout(legend_traceorder="reversed",)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(supply_df, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                              value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG         83.0
                                  H2m1.0+H2v1.0+3H            2050 EG         83.0
                                  H2m1.0+NH3v1.0+3H           2050 EG         83.0
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG         85.6
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       2414.3

In [31]:
df = prepare_dataframe(optimal_capacity_dict["AC"], idx_group, set_scen_col)
df = df[df["value"]<1e6] #drop loadshedding capacity
df.variable = df.variable.map(rename_electricity).map(rename_to_upper_case)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [32]:
fig_name = "electricity_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    #barmode="stack",
    color_discrete_map=colors["electricity"],
    category_orders={
        "variable":list(colors["electricity"].keys()),
        "scen": scen_order
        },
    #facet_col_spacing=0.1,
    #range_y=(0,supply_sum_df.max().value*1.1),
    labels={"value":"Installed capacity in GW<sub>el</sub>","year":"",
            #"variable":"",
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG       27768.2
                                  H2m1.0+H2v1.0+3H            2050 EG       27820.0
                                  H2m1.0+NH3v1.0+3H           2050 EG       27827.4
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG       27836.9
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       38677.6

In [33]:
df = prepare_dataframe(optimal_capacity_dict["H2"], idx_group, set_scen_col)
df = df[df["value"]<1e6] #drop loadshedding capacity
df.variable = df.variable.map(rename_h2)

(supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df)

In [34]:
fig_name = "hydrogen_installed_capacity_GW"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map={"H2 Electrolysis":"#179c7d"},
    category_orders={
        #"variable":list(colors["gas"].keys())
        "scen": scen_order
        },
    labels={"value":"Installed capacity in GW<sub>H2</sub>","year":"","variable":"","scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_{fig_name}")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG       27117.5
                                  H2m1.0+H2v1.0+3H            2050 EG       27133.9
                                  H2m1.0+NH3v1.0+3H           2050 EG       27136.0
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG       27139.1
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       29963.3

In [35]:
stats_df = pd.concat([costs_dict["capex"],costs_dict["opex"]],axis=0)
df = prepare_dataframe(stats_df, idx_group, set_scen_col)
df.variable = df.variable.map(rename_costs) # ToDo rename important cost components
df = df.groupby(["run_name_prefix", "scen", "year", "country", "variable"], as_index=False).sum().round(1)
df = df[df["value"]!=0]

# (supply_df, supply_sum_df, demand_df, demand_sum_df) = get_supply_demand_from_balance(df, threshold=0., round=1)

In [ ]:
fig_name = "system_costs_billion_eur" # expenditure and export revenue
fig_kwargs["height"] = heights["3"]
fig_kwargs["text_auto"] = ".1f"
fig = px.bar(
    df, 
    **fig_kwargs,
    color_discrete_map=colors["costs"],
    category_orders={
        "variable":list(colors["costs"].keys()),
        #"scen": scen_order
        },
    facet_col_spacing=0.1,
    labels={"value":"System costs in billion EUR20XX/year","year":"", 
            #"variable":"", 
            "scen":""},
)
update_layout(fig)

print("Totals per scenario and year:", supply_sum_df)
fig.show()
#save_plotly_fig(df, fig, fig, sdir, f"{idx_group_name}_installed_capacity_AC_GW")

Totals per scenario and year:                                                                               value
run_name_prefix run_name          scen                        year country
DKS             DKS_EG_2050_eopts H2m1.0+H2v0.5+3H            2050 EG       27117.5
                                  H2m1.0+H2v1.0+3H            2050 EG       27133.9
                                  H2m1.0+NH3v1.0+3H           2050 EG       27136.0
                                  H2m1.0+NH3v1.0+FTv1.0+3H    2050 EG       27139.1
                                  H2v1.01+NH3v1.01+FTv1.01+3H 2050 EG       29963.3

:

## Relative costs

costs / total energy consumption

## Water consumption